/**
 * Purchase Requests Mock Data
 *
 * Transaction Code Format: PREFIX-YYMM-NNNN
 * - PREFIX: Document type identifier (PR = Purchase Request, FB/HK/etc = Job Code prefix)
 * - YY: Two-digit year (e.g., 24 for 2024)
 * - MM: Two-digit month (e.g., 10 for October)
 * - NNNN: Sequential number (e.g., 001, 002, etc.)
 * Example: PR-2410-001 = Purchase Request #001 from October 2024
 */

import { PRType, PRStatus, WorkflowStatus, WorkflowStage, MockPurchaseRequest, MockPurchaseRequestItem } from '@/lib/types'

// Sample Purchase Request with transaction code format PR-YYMM-NNNN
export const samplePRData: MockPurchaseRequest = {
  id: 'sample-pr-001',
  refNumber: 'PR-2310-001',
  requestNumber: 'PR-2310-001',
  requestDate: new Date('2023-01-01'),
  requiredDate: new Date('2023-01-15'),
  requestType: 'General',
  priority: 'normal',
  justification: 'Sample purchase request for office supplies',
  requestedBy: 'user-001',
  departmentId: 'dept-001',
  locationId: 'loc-001',
  totalItems: 10,
  estimatedTotal: { amount: 1100, currency: 'USD' },
  workflowStages: [],
  requestor: {
    name: 'John Doe',
    department: 'Administration'
  },
  status: PRStatus.Draft,
  currentWorkflowStage: WorkflowStage.requester,
  location: 'Head Office',
  department: 'Administration',
  jobCode: 'JOB-001',
  currency: 'USD',
  baseCurrencyCode: 'USD',
  baseSubTotalPrice: 1000,
  subTotalPrice: 1000,
  baseNetAmount: 1000,
  netAmount: 1000,
  baseDiscAmount: 0,
  discountAmount: 0,
  baseTaxAmount: 100,
  taxAmount: 100,
  baseTotalAmount: 1100,
  totalAmount: 1100,
}

export const samplePRItems: MockPurchaseRequestItem[] = [
  {
    id: "PR-2310-001-01",
    requestId: "sample-pr-001",
    itemName: "Premium Coffee Beans",
    location: "Main Kitchen",
    name: "Premium Coffee Beans",
    description: "Arabica beans, medium roast, 1kg bags",
    unit: "kg",
    requestedQuantity: 25,
    quantityRequested: 25,
    quantityApproved: 20,
    deliveryLocationId: "main-kitchen",
    requiredDate: new Date("2023-07-01"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 15,
      onOrdered: 30,
      lastPrice: 14.50,
      lastOrderDate: new Date("2023-05-10"),
      lastVendor: "Global F&B Suppliers",
      reorderLevel: 20,
      restockLevel: 80,
      averageMonthlyUsage: 45,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 15.50,
    totalAmount: 310.00,
    status: PRStatus.Approved,
    taxRate: 0.10,
    taxAmount: 31.00,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 341.00,
    deliveryDate: new Date("2023-07-01"),
    deliveryPoint: "Main Kitchen Storage",
    jobCode: "FB-2310-001",
    createdDate: new Date("2023-06-01"),
    updatedDate: new Date("2023-06-15"),
    createdBy: "John Chef",
    updatedBy: "Jane Manager",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Beverages",
    vendor: "Global F&B Suppliers",
    pricelistNumber: "PL-2310-06-FB",
    comment: "For breakfast and meeting services",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FB-1001",
  },
  {
    id: "PR-2310-001-02",
    requestId: "sample-pr-001",
    itemName: "All Purpose Flour",
    location: "Dry Storage",
    name: "All Purpose Flour",
    description: "Premium quality baking flour, 25kg sacks",
    unit: "kg",
    requestedQuantity: 100,
    quantityRequested: 100,
    quantityApproved: 100,
    deliveryLocationId: "dry-storage",
    requiredDate: new Date("2023-07-03"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 50,
      onOrdered: 200,
      lastPrice: 2.80,
      lastOrderDate: new Date("2023-05-15"),
      lastVendor: "Baking Supplies Co.",
      reorderLevel: 75,
      restockLevel: 300,
      averageMonthlyUsage: 120,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 3.00,
    totalAmount: 300.00,
    status: PRStatus.InProgress,
    taxRate: 0.08,
    taxAmount: 24.00,
    discountRate: 0.05,
    discountAmount: 15.00,
    netAmount: 309.00,
    deliveryDate: new Date("2023-07-03"),
    deliveryPoint: "Dry Storage Area",
    jobCode: "FB-2310-002",
    createdDate: new Date("2023-06-02"),
    updatedDate: new Date("2023-06-16"),
    createdBy: "Alice Baker",
    updatedBy: "Bob Supervisor",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Dry Goods",
    vendor: "Baking Supplies Co.",
    pricelistNumber: "PL-2310-06-BAKE",
    comment: "For daily bread and pastry production",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FB-2001",
  },
  {
    id: "PR-2310-001-03",
    requestId: "sample-pr-001",
    itemName: "Fresh Atlantic Salmon",
    location: "Cold Storage",
    name: "Fresh Atlantic Salmon",
    description: "Premium salmon fillets, fresh daily delivery",
    unit: "kg",
    requestedQuantity: 20,
    quantityRequested: 20,
    quantityApproved: 18,
    deliveryLocationId: "cold-storage",
    requiredDate: new Date("2023-07-02"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 5,
      onOrdered: 25,
      lastPrice: 22.00,
      lastOrderDate: new Date("2023-06-10"),
      lastVendor: "Ocean Fresh Seafood",
      reorderLevel: 10,
      restockLevel: 30,
      averageMonthlyUsage: 35,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 24.50,
    totalAmount: 441.00,
    status: PRStatus.Approved,
    taxRate: 0.10,
    taxAmount: 44.10,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 485.10,
    deliveryDate: new Date("2023-07-02"),
    deliveryPoint: "Cold Storage Room B",
    jobCode: "FB-2310-003",
    createdDate: new Date("2023-06-03"),
    updatedDate: new Date("2023-06-17"),
    createdBy: "Mike Fishmonger",
    updatedBy: "Sarah Manager",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Seafood",
    vendor: "Ocean Fresh Seafood",
    pricelistNumber: "PL-2310-06-SEA",
    comment: "For special dinner menu and catering events",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FB-3001",
  },
  {
    id: "PR-2310-001-04",
    requestId: "sample-pr-001",
    itemName: "Premium Bath Towels",
    location: "Housekeeping Storage",
    name: "Premium Bath Towels",
    description: "100% cotton, 600 GSM, white, hotel grade",
    unit: "piece",
    requestedQuantity: 50,
    quantityRequested: 50,
    quantityApproved: 45,
    deliveryLocationId: "housekeeping-storage",
    requiredDate: new Date("2023-07-05"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 20,
      onOrdered: 100,
      lastPrice: 18.00,
      lastOrderDate: new Date("2023-05-20"),
      lastVendor: "Hotel Linen Co.",
      reorderLevel: 30,
      restockLevel: 100,
      averageMonthlyUsage: 25,
      inventoryUnit: "piece",
    },
    currency: "USD",
    price: 19.50,
    totalAmount: 877.50,
    status: PRStatus.InProgress,
    taxRate: 0.08,
    taxAmount: 70.20,
    discountRate: 0.10,
    discountAmount: 87.75,
    netAmount: 859.95,
    deliveryDate: new Date("2023-07-05"),
    deliveryPoint: "Housekeeping Main Storage",
    jobCode: "HK-2310-001",
    createdDate: new Date("2023-06-04"),
    updatedDate: new Date("2023-06-18"),
    createdBy: "Lisa Housekeeper",
    updatedBy: "Tom Supervisor",
    itemCategory: "Housekeeping",
    itemSubcategory: "Linens",
    vendor: "Hotel Linen Co.",
    pricelistNumber: "PL-2310-06-LINEN",
    comment: "Replacement for worn towels in guest rooms",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "HK-1001",
  },
  {
    id: "PR-2310-001-05",
    requestId: "sample-pr-001",
    itemName: "LED Light Bulbs",
    location: "Maintenance Workshop",
    name: "LED Light Bulbs",
    description: "Energy efficient LED bulbs, 60W equivalent, warm white",
    unit: "piece",
    requestedQuantity: 100,
    quantityRequested: 100,
    quantityApproved: 80,
    deliveryLocationId: "maintenance-workshop",
    requiredDate: new Date("2023-07-04"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 25,
      onOrdered: 150,
      lastPrice: 8.50,
      lastOrderDate: new Date("2023-04-25"),
      lastVendor: "Electrical Supplies Inc.",
      reorderLevel: 50,
      restockLevel: 200,
      averageMonthlyUsage: 60,
      inventoryUnit: "piece",
    },
    currency: "USD",
    price: 9.00,
    totalAmount: 720.00,
    status: PRStatus.Approved,
    taxRate: 0.08,
    taxAmount: 57.60,
    discountRate: 0.15,
    discountAmount: 108.00,
    netAmount: 669.60,
    deliveryDate: new Date("2023-07-04"),
    deliveryPoint: "Maintenance Storage Room",
    jobCode: "MAINT-2310-001",
    createdDate: new Date("2023-06-05"),
    updatedDate: new Date("2023-06-19"),
    createdBy: "David Electrician",
    updatedBy: "Mark Supervisor",
    itemCategory: "Maintenance",
    itemSubcategory: "Electrical",
    vendor: "Electrical Supplies Inc.",
    pricelistNumber: "PL-2310-06-ELEC",
    comment: "Upgrade to energy-efficient lighting throughout property",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "MAINT-1001",
  },
  {
    id: "PR-2310-001-06",
    requestId: "sample-pr-001",
    itemName: "Premium Whiskey Collection",
    location: "Bar Storage",
    name: "Premium Whiskey Collection",
    description: "Single malt whiskey selection for VIP guests",
    unit: "bottle",
    requestedQuantity: 12,
    quantityRequested: 12,
    quantityApproved: 0,
    deliveryLocationId: "bar-storage",
    requiredDate: new Date("2023-07-10"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 125.00,
      lastOrderDate: new Date("2023-04-15"),
      lastVendor: "Premium Spirits Ltd.",
      reorderLevel: 8,
      restockLevel: 20,
      averageMonthlyUsage: 15,
      inventoryUnit: "bottle",
    },
    currency: "USD",
    price: 135.00,
    totalAmount: 1620.00,
    status: PRStatus.Draft,
    taxRate: 0.12,
    taxAmount: 194.40,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 1814.40,
    deliveryDate: new Date("2023-07-10"),
    deliveryPoint: "Bar Storage Room",
    jobCode: "BAR-2310-001",
    createdDate: new Date("2023-06-06"),
    updatedDate: new Date("2023-06-06"),
    createdBy: "Emma Bartender",
    updatedBy: "Emma Bartender",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Spirits",
    vendor: "Premium Spirits Ltd.",
    pricelistNumber: "PL-2310-06-SPIRITS",
    comment: "Requested for upcoming VIP events and special occasions",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "BAR-1001",
  },
  {
    id: "PR-2310-001-07",
    requestId: "sample-pr-001",
    itemName: "RFID Key Cards",
    location: "Front Desk Storage",
    name: "RFID Key Cards",
    description: "Hotel access cards with magnetic stripe backup",
    unit: "pack",
    requestedQuantity: 20,
    quantityRequested: 20,
    quantityApproved: 0,
    deliveryLocationId: "front-desk",
    requiredDate: new Date("2023-07-08"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 8,
      onOrdered: 0,
      lastPrice: 45.00,
      lastOrderDate: new Date("2023-03-20"),
      lastVendor: "SecureAccess Systems",
      reorderLevel: 10,
      restockLevel: 30,
      averageMonthlyUsage: 12,
      inventoryUnit: "pack",
    },
    currency: "USD",
    price: 48.00,
    totalAmount: 960.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 76.80,
    discountRate: 0.05,
    discountAmount: 48.00,
    netAmount: 988.80,
    deliveryDate: new Date("2023-07-08"),
    deliveryPoint: "Front Desk Storage",
    jobCode: "FO-2310-001",
    createdDate: new Date("2023-06-07"),
    updatedDate: new Date("2023-06-07"),
    createdBy: "Rachel Receptionist",
    updatedBy: "Rachel Receptionist",
    itemCategory: "Front Office",
    itemSubcategory: "Access Control",
    vendor: "SecureAccess Systems",
    pricelistNumber: "PL-2310-06-SECURITY",
    comment: "Running low on key cards, need restock before summer season",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FO-1001",
  },
  {
    id: "PR-2310-001-08",
    requestId: "sample-pr-001",
    itemName: "Professional Chef Knives Set",
    location: "Restaurant Kitchen",
    name: "Professional Chef Knives Set",
    description: "High-carbon stainless steel knife set with storage block",
    unit: "set",
    requestedQuantity: 3,
    quantityRequested: 3,
    quantityApproved: 0,
    deliveryLocationId: "restaurant-kitchen",
    requiredDate: new Date("2023-07-12"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 1,
      onOrdered: 0,
      lastPrice: 280.00,
      lastOrderDate: new Date("2023-02-10"),
      lastVendor: "Professional Kitchen Supply",
      reorderLevel: 2,
      restockLevel: 5,
      averageMonthlyUsage: 1,
      inventoryUnit: "set",
    },
    currency: "USD",
    price: 295.00,
    totalAmount: 885.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 70.80,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 955.80,
    deliveryDate: new Date("2023-07-12"),
    deliveryPoint: "Kitchen Equipment Storage",
    jobCode: "KITCHEN-2310-001",
    createdDate: new Date("2023-06-08"),
    updatedDate: new Date("2023-06-08"),
    createdBy: "Carlos Chef",
    updatedBy: "Carlos Chef",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Kitchen Equipment",
    vendor: "Professional Kitchen Supply",
    pricelistNumber: "PL-2310-06-KITCHEN",
    comment: "Additional knife sets needed for new kitchen staff",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "KITCHEN-1001",
  },
  {
    id: "PR-2310-001-09",
    requestId: "sample-pr-001",
    itemName: "Pool Cleaning Chemicals",
    location: "Pool Area Storage",
    name: "Pool Cleaning Chemicals",
    description: "Chlorine tablets, pH balancers, and algae treatment",
    unit: "kit",
    requestedQuantity: 5,
    quantityRequested: 5,
    quantityApproved: 0,
    deliveryLocationId: "pool-area",
    requiredDate: new Date("2023-07-06"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 2,
      onOrdered: 0,
      lastPrice: 85.00,
      lastOrderDate: new Date("2023-05-05"),
      lastVendor: "Pool Maintenance Co.",
      reorderLevel: 3,
      restockLevel: 10,
      averageMonthlyUsage: 8,
      inventoryUnit: "kit",
    },
    currency: "USD",
    price: 92.00,
    totalAmount: 460.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 36.80,
    discountRate: 0.10,
    discountAmount: 46.00,
    netAmount: 450.80,
    deliveryDate: new Date("2023-07-06"),
    deliveryPoint: "Pool Equipment Room",
    jobCode: "POOL-2310-001",
    createdDate: new Date("2023-06-09"),
    updatedDate: new Date("2023-06-09"),
    createdBy: "Steve Pool Attendant",
    updatedBy: "Steve Pool Attendant",
    itemCategory: "Maintenance",
    itemSubcategory: "Pool Supplies",
    vendor: "Pool Maintenance Co.",
    pricelistNumber: "PL-2310-06-POOL",
    comment: "Essential for maintaining pool water quality during peak season",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "POOL-1001",
  },
  {
    id: "PR-2310-001-10",
    requestId: "sample-pr-001",
    itemName: "Commercial Laundry Detergent",
    location: "Laundry Room",
    name: "Commercial Laundry Detergent",
    description: "Heavy-duty detergent for hotel linens, 20kg drums",
    unit: "drum",
    requestedQuantity: 8,
    quantityRequested: 8,
    quantityApproved: 0,
    deliveryLocationId: "laundry-room",
    requiredDate: new Date("2023-07-07"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 65.00,
      lastOrderDate: new Date("2023-04-30"),
      lastVendor: "Industrial Cleaning Supplies",
      reorderLevel: 5,
      restockLevel: 15,
      averageMonthlyUsage: 10,
      inventoryUnit: "drum",
    },
    currency: "USD",
    price: 68.00,
    totalAmount: 544.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 43.52,
    discountRate: 0.08,
    discountAmount: 43.52,
    netAmount: 543.52,
    deliveryDate: new Date("2023-07-07"),
    deliveryPoint: "Laundry Storage Area",
    jobCode: "LAUNDRY-2310-001",
    createdDate: new Date("2023-06-10"),
    updatedDate: new Date("2023-06-10"),
    createdBy: "Maria Laundry Supervisor",
    updatedBy: "Maria Laundry Supervisor",
    itemCategory: "Housekeeping",
    itemSubcategory: "Cleaning Supplies",
    vendor: "Industrial Cleaning Supplies",
    pricelistNumber: "PL-2310-06-CLEAN",
    comment: "Need to restock before busy summer period begins",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "LAUNDRY-1001",
  },
];

export const mockPurchaseRequests: MockPurchaseRequest[] = [samplePRData];
export const mockPurchaseRequestItems: MockPurchaseRequestItem[] = samplePRItems;
