/**
 * Purchase Requests Mock Data
 *
 * Transaction Code Format: PREFIX-YYMM-NNNN
 * - PREFIX: Document type identifier (PR = Purchase Request, FB/HK/etc = Job Code prefix)
 * - YY: Two-digit year (e.g., 24 for 2024)
 * - MM: Two-digit month (e.g., 10 for October)
 * - NNNN: Sequential number (e.g., 001, 002, etc.)
 * Example: PR-2410-001 = Purchase Request #001 from October 2024
 */

import { PRType, PRStatus, WorkflowStatus, WorkflowStage, MockPurchaseRequest, MockPurchaseRequestItem } from '@/lib/types'

// Sample Purchase Request with transaction code format PR-YYMM-NNNN
export const samplePRData: MockPurchaseRequest = {
  id: 'sample-pr-001',
  refNumber: 'PR-2310-001',
  requestNumber: 'PR-2310-001',
  requestDate: new Date('2023-01-01'),
  requiredDate: new Date('2023-01-15'),
  requestType: 'General',
  priority: 'normal',
  justification: 'Sample purchase request for office supplies',
  requestedBy: 'user-001',
  departmentId: 'dept-001',
  locationId: 'loc-001',
  totalItems: 10,
  estimatedTotal: { amount: 1100, currency: 'USD' },
  workflowStages: [],
  requestor: {
    name: 'John Doe',
    department: 'Administration'
  },
  status: PRStatus.Draft,
  currentWorkflowStage: WorkflowStage.requester,
  location: 'Head Office',
  department: 'Administration',
  jobCode: 'JOB-001',
  currency: 'USD',
  baseCurrencyCode: 'USD',
  baseSubTotalPrice: 1000,
  subTotalPrice: 1000,
  baseNetAmount: 1000,
  netAmount: 1000,
  baseDiscAmount: 0,
  discountAmount: 0,
  baseTaxAmount: 100,
  taxAmount: 100,
  baseTotalAmount: 1100,
  totalAmount: 1100,
}

export const samplePRItems: MockPurchaseRequestItem[] = [
  {
    id: "PR-2310-001-01",
    requestId: "sample-pr-001",
    itemName: "Premium Coffee Beans",
    location: "Main Kitchen",
    name: "Premium Coffee Beans",
    description: "Arabica beans, medium roast, 1kg bags",
    unit: "kg",
    requestedQuantity: 25,
    quantityRequested: 25,
    quantityApproved: 20,
    deliveryLocationId: "main-kitchen",
    requiredDate: new Date("2023-07-01"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 15,
      onOrdered: 30,
      lastPrice: 14.50,
      lastOrderDate: new Date("2023-05-10"),
      lastVendor: "Global F&B Suppliers",
      reorderLevel: 20,
      restockLevel: 80,
      averageMonthlyUsage: 45,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 15.50,
    totalAmount: 310.00,
    status: PRStatus.Approved,
    taxRate: 0.10,
    taxAmount: 31.00,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 341.00,
    deliveryDate: new Date("2023-07-01"),
    deliveryPoint: "Main Kitchen Storage",
    jobCode: "FB-2310-001",
    createdDate: new Date("2023-06-01"),
    updatedDate: new Date("2023-06-15"),
    createdBy: "John Chef",
    updatedBy: "Jane Manager",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Beverages",
    vendor: "Global F&B Suppliers",
    pricelistNumber: "PL-2310-06-FB",
    comment: "For breakfast and meeting services",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FB-1001",
  },
  {
    id: "PR-2310-001-02",
    requestId: "sample-pr-001",
    itemName: "All Purpose Flour",
    location: "Dry Storage",
    name: "All Purpose Flour",
    description: "Premium quality baking flour, 25kg sacks",
    unit: "kg",
    requestedQuantity: 100,
    quantityRequested: 100,
    quantityApproved: 100,
    deliveryLocationId: "dry-storage",
    requiredDate: new Date("2023-07-03"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 50,
      onOrdered: 200,
      lastPrice: 2.80,
      lastOrderDate: new Date("2023-05-15"),
      lastVendor: "Baking Supplies Co.",
      reorderLevel: 75,
      restockLevel: 300,
      averageMonthlyUsage: 120,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 3.00,
    totalAmount: 300.00,
    status: PRStatus.InProgress,
    taxRate: 0.08,
    taxAmount: 24.00,
    discountRate: 0.05,
    discountAmount: 15.00,
    netAmount: 309.00,
    deliveryDate: new Date("2023-07-03"),
    deliveryPoint: "Dry Storage Area",
    jobCode: "FB-2310-002",
    createdDate: new Date("2023-06-02"),
    updatedDate: new Date("2023-06-16"),
    createdBy: "Alice Baker",
    updatedBy: "Bob Supervisor",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Dry Goods",
    vendor: "Baking Supplies Co.",
    pricelistNumber: "PL-2310-06-BAKE",
    comment: "For daily bread and pastry production",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FB-2001",
  },
  {
    id: "PR-2310-001-03",
    requestId: "sample-pr-001",
    itemName: "Fresh Atlantic Salmon",
    location: "Cold Storage",
    name: "Fresh Atlantic Salmon",
    description: "Premium salmon fillets, fresh daily delivery",
    unit: "kg",
    requestedQuantity: 20,
    quantityRequested: 20,
    quantityApproved: 18,
    deliveryLocationId: "cold-storage",
    requiredDate: new Date("2023-07-02"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 5,
      onOrdered: 25,
      lastPrice: 22.00,
      lastOrderDate: new Date("2023-06-10"),
      lastVendor: "Ocean Fresh Seafood",
      reorderLevel: 10,
      restockLevel: 30,
      averageMonthlyUsage: 35,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 24.50,
    totalAmount: 441.00,
    status: PRStatus.Approved,
    taxRate: 0.10,
    taxAmount: 44.10,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 485.10,
    deliveryDate: new Date("2023-07-02"),
    deliveryPoint: "Cold Storage Room B",
    jobCode: "FB-2310-003",
    createdDate: new Date("2023-06-03"),
    updatedDate: new Date("2023-06-17"),
    createdBy: "Mike Fishmonger",
    updatedBy: "Sarah Manager",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Seafood",
    vendor: "Ocean Fresh Seafood",
    pricelistNumber: "PL-2310-06-SEA",
    comment: "For special dinner menu and catering events",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FB-3001",
  },
  {
    id: "PR-2310-001-04",
    requestId: "sample-pr-001",
    itemName: "Premium Bath Towels",
    location: "Housekeeping Storage",
    name: "Premium Bath Towels",
    description: "100% cotton, 600 GSM, white, hotel grade",
    unit: "piece",
    requestedQuantity: 50,
    quantityRequested: 50,
    quantityApproved: 45,
    deliveryLocationId: "housekeeping-storage",
    requiredDate: new Date("2023-07-05"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 20,
      onOrdered: 100,
      lastPrice: 18.00,
      lastOrderDate: new Date("2023-05-20"),
      lastVendor: "Hotel Linen Co.",
      reorderLevel: 30,
      restockLevel: 100,
      averageMonthlyUsage: 25,
      inventoryUnit: "piece",
    },
    currency: "USD",
    price: 19.50,
    totalAmount: 877.50,
    status: PRStatus.InProgress,
    taxRate: 0.08,
    taxAmount: 70.20,
    discountRate: 0.10,
    discountAmount: 87.75,
    netAmount: 859.95,
    deliveryDate: new Date("2023-07-05"),
    deliveryPoint: "Housekeeping Main Storage",
    jobCode: "HK-2310-001",
    createdDate: new Date("2023-06-04"),
    updatedDate: new Date("2023-06-18"),
    createdBy: "Lisa Housekeeper",
    updatedBy: "Tom Supervisor",
    itemCategory: "Housekeeping",
    itemSubcategory: "Linens",
    vendor: "Hotel Linen Co.",
    pricelistNumber: "PL-2310-06-LINEN",
    comment: "Replacement for worn towels in guest rooms",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "HK-1001",
  },
  {
    id: "PR-2310-001-05",
    requestId: "sample-pr-001",
    itemName: "LED Light Bulbs",
    location: "Maintenance Workshop",
    name: "LED Light Bulbs",
    description: "Energy efficient LED bulbs, 60W equivalent, warm white",
    unit: "piece",
    requestedQuantity: 100,
    quantityRequested: 100,
    quantityApproved: 80,
    deliveryLocationId: "maintenance-workshop",
    requiredDate: new Date("2023-07-04"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 25,
      onOrdered: 150,
      lastPrice: 8.50,
      lastOrderDate: new Date("2023-04-25"),
      lastVendor: "Electrical Supplies Inc.",
      reorderLevel: 50,
      restockLevel: 200,
      averageMonthlyUsage: 60,
      inventoryUnit: "piece",
    },
    currency: "USD",
    price: 9.00,
    totalAmount: 720.00,
    status: PRStatus.Approved,
    taxRate: 0.08,
    taxAmount: 57.60,
    discountRate: 0.15,
    discountAmount: 108.00,
    netAmount: 669.60,
    deliveryDate: new Date("2023-07-04"),
    deliveryPoint: "Maintenance Storage Room",
    jobCode: "MAINT-2310-001",
    createdDate: new Date("2023-06-05"),
    updatedDate: new Date("2023-06-19"),
    createdBy: "David Electrician",
    updatedBy: "Mark Supervisor",
    itemCategory: "Maintenance",
    itemSubcategory: "Electrical",
    vendor: "Electrical Supplies Inc.",
    pricelistNumber: "PL-2310-06-ELEC",
    comment: "Upgrade to energy-efficient lighting throughout property",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "MAINT-1001",
  },
  {
    id: "PR-2310-001-06",
    requestId: "sample-pr-001",
    itemName: "Premium Whiskey Collection",
    location: "Bar Storage",
    name: "Premium Whiskey Collection",
    description: "Single malt whiskey selection for VIP guests",
    unit: "bottle",
    requestedQuantity: 12,
    quantityRequested: 12,
    quantityApproved: 0,
    deliveryLocationId: "bar-storage",
    requiredDate: new Date("2023-07-10"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 125.00,
      lastOrderDate: new Date("2023-04-15"),
      lastVendor: "Premium Spirits Ltd.",
      reorderLevel: 8,
      restockLevel: 20,
      averageMonthlyUsage: 15,
      inventoryUnit: "bottle",
    },
    currency: "USD",
    price: 135.00,
    totalAmount: 1620.00,
    status: PRStatus.Draft,
    taxRate: 0.12,
    taxAmount: 194.40,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 1814.40,
    deliveryDate: new Date("2023-07-10"),
    deliveryPoint: "Bar Storage Room",
    jobCode: "BAR-2310-001",
    createdDate: new Date("2023-06-06"),
    updatedDate: new Date("2023-06-06"),
    createdBy: "Emma Bartender",
    updatedBy: "Emma Bartender",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Spirits",
    vendor: "Premium Spirits Ltd.",
    pricelistNumber: "PL-2310-06-SPIRITS",
    comment: "Requested for upcoming VIP events and special occasions",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "BAR-1001",
  },
  {
    id: "PR-2310-001-07",
    requestId: "sample-pr-001",
    itemName: "RFID Key Cards",
    location: "Front Desk Storage",
    name: "RFID Key Cards",
    description: "Hotel access cards with magnetic stripe backup",
    unit: "pack",
    requestedQuantity: 20,
    quantityRequested: 20,
    quantityApproved: 0,
    deliveryLocationId: "front-desk",
    requiredDate: new Date("2023-07-08"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 8,
      onOrdered: 0,
      lastPrice: 45.00,
      lastOrderDate: new Date("2023-03-20"),
      lastVendor: "SecureAccess Systems",
      reorderLevel: 10,
      restockLevel: 30,
      averageMonthlyUsage: 12,
      inventoryUnit: "pack",
    },
    currency: "USD",
    price: 48.00,
    totalAmount: 960.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 76.80,
    discountRate: 0.05,
    discountAmount: 48.00,
    netAmount: 988.80,
    deliveryDate: new Date("2023-07-08"),
    deliveryPoint: "Front Desk Storage",
    jobCode: "FO-2310-001",
    createdDate: new Date("2023-06-07"),
    updatedDate: new Date("2023-06-07"),
    createdBy: "Rachel Receptionist",
    updatedBy: "Rachel Receptionist",
    itemCategory: "Front Office",
    itemSubcategory: "Access Control",
    vendor: "SecureAccess Systems",
    pricelistNumber: "PL-2310-06-SECURITY",
    comment: "Running low on key cards, need restock before summer season",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "FO-1001",
  },
  {
    id: "PR-2310-001-08",
    requestId: "sample-pr-001",
    itemName: "Professional Chef Knives Set",
    location: "Restaurant Kitchen",
    name: "Professional Chef Knives Set",
    description: "High-carbon stainless steel knife set with storage block",
    unit: "set",
    requestedQuantity: 3,
    quantityRequested: 3,
    quantityApproved: 0,
    deliveryLocationId: "restaurant-kitchen",
    requiredDate: new Date("2023-07-12"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 1,
      onOrdered: 0,
      lastPrice: 280.00,
      lastOrderDate: new Date("2023-02-10"),
      lastVendor: "Professional Kitchen Supply",
      reorderLevel: 2,
      restockLevel: 5,
      averageMonthlyUsage: 1,
      inventoryUnit: "set",
    },
    currency: "USD",
    price: 295.00,
    totalAmount: 885.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 70.80,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 955.80,
    deliveryDate: new Date("2023-07-12"),
    deliveryPoint: "Kitchen Equipment Storage",
    jobCode: "KITCHEN-2310-001",
    createdDate: new Date("2023-06-08"),
    updatedDate: new Date("2023-06-08"),
    createdBy: "Carlos Chef",
    updatedBy: "Carlos Chef",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Kitchen Equipment",
    vendor: "Professional Kitchen Supply",
    pricelistNumber: "PL-2310-06-KITCHEN",
    comment: "Additional knife sets needed for new kitchen staff",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "KITCHEN-1001",
  },
  {
    id: "PR-2310-001-09",
    requestId: "sample-pr-001",
    itemName: "Pool Cleaning Chemicals",
    location: "Pool Area Storage",
    name: "Pool Cleaning Chemicals",
    description: "Chlorine tablets, pH balancers, and algae treatment",
    unit: "kit",
    requestedQuantity: 5,
    quantityRequested: 5,
    quantityApproved: 0,
    deliveryLocationId: "pool-area",
    requiredDate: new Date("2023-07-06"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 2,
      onOrdered: 0,
      lastPrice: 85.00,
      lastOrderDate: new Date("2023-05-05"),
      lastVendor: "Pool Maintenance Co.",
      reorderLevel: 3,
      restockLevel: 10,
      averageMonthlyUsage: 8,
      inventoryUnit: "kit",
    },
    currency: "USD",
    price: 92.00,
    totalAmount: 460.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 36.80,
    discountRate: 0.10,
    discountAmount: 46.00,
    netAmount: 450.80,
    deliveryDate: new Date("2023-07-06"),
    deliveryPoint: "Pool Equipment Room",
    jobCode: "POOL-2310-001",
    createdDate: new Date("2023-06-09"),
    updatedDate: new Date("2023-06-09"),
    createdBy: "Steve Pool Attendant",
    updatedBy: "Steve Pool Attendant",
    itemCategory: "Maintenance",
    itemSubcategory: "Pool Supplies",
    vendor: "Pool Maintenance Co.",
    pricelistNumber: "PL-2310-06-POOL",
    comment: "Essential for maintaining pool water quality during peak season",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "POOL-1001",
  },
  {
    id: "PR-2310-001-10",
    requestId: "sample-pr-001",
    itemName: "Commercial Laundry Detergent",
    location: "Laundry Room",
    name: "Commercial Laundry Detergent",
    description: "Heavy-duty detergent for hotel linens, 20kg drums",
    unit: "drum",
    requestedQuantity: 8,
    quantityRequested: 8,
    quantityApproved: 0,
    deliveryLocationId: "laundry-room",
    requiredDate: new Date("2023-07-07"),
    priority: "normal" as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 65.00,
      lastOrderDate: new Date("2023-04-30"),
      lastVendor: "Industrial Cleaning Supplies",
      reorderLevel: 5,
      restockLevel: 15,
      averageMonthlyUsage: 10,
      inventoryUnit: "drum",
    },
    currency: "USD",
    price: 68.00,
    totalAmount: 544.00,
    status: PRStatus.Draft,
    taxRate: 0.08,
    taxAmount: 43.52,
    discountRate: 0.08,
    discountAmount: 43.52,
    netAmount: 543.52,
    deliveryDate: new Date("2023-07-07"),
    deliveryPoint: "Laundry Storage Area",
    jobCode: "LAUNDRY-2310-001",
    createdDate: new Date("2023-06-10"),
    updatedDate: new Date("2023-06-10"),
    createdBy: "Maria Laundry Supervisor",
    updatedBy: "Maria Laundry Supervisor",
    itemCategory: "Housekeeping",
    itemSubcategory: "Cleaning Supplies",
    vendor: "Industrial Cleaning Supplies",
    pricelistNumber: "PL-2310-06-CLEAN",
    comment: "Need to restock before busy summer period begins",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: "LAUNDRY-1001",
  },
];

// ====== SR-GENERATED PURCHASE REQUESTS ======
// These PRs were generated from Store Requisitions when stock was insufficient

/**
 * PR-2412-015: Generated from SR-2412-002 (partial fulfillment)
 * 30kg Organic Tomatoes shortage - stock had 20kg, needed 50kg
 */
export const prFromSR002: MockPurchaseRequest = {
  id: 'pr-015',
  refNumber: 'PR-2412-015',
  requestNumber: 'PR-2412-015',
  requestDate: new Date('2024-12-05'),
  requiredDate: new Date('2024-12-08'),
  requestType: 'General',
  priority: 'normal',
  justification: 'Stock shortage from Store Requisition SR-2412-002 - partial stock transfer completed, PR for remaining quantity',
  requestedBy: 'user-chef-001',
  departmentId: 'dept-003',
  locationId: 'loc-003',
  totalItems: 1,
  estimatedTotal: { amount: 97.50, currency: 'USD' },
  workflowStages: [],
  requestor: {
    name: 'Chef Maria Rodriguez',
    department: 'Food & Beverage'
  },
  status: PRStatus.InProgress,
  currentWorkflowStage: WorkflowStage.departmentHeadApproval,
  location: 'Central Kitchen',
  department: 'Food & Beverage',
  currency: 'USD',
  baseCurrencyCode: 'USD',
  baseSubTotalPrice: 97.50,
  subTotalPrice: 97.50,
  baseNetAmount: 97.50,
  netAmount: 97.50,
  baseDiscAmount: 0,
  discountAmount: 0,
  baseTaxAmount: 0,
  taxAmount: 0,
  baseTotalAmount: 97.50,
  totalAmount: 97.50,
  // Source requisition tracking
  sourceRequisitionId: 'sr-002',
  sourceRequisitionRefNo: 'SR-2412-002',
  sourceRequisitionItemIds: ['sri-002-01'],
}

export const prFromSR002Items: MockPurchaseRequestItem[] = [
  {
    id: 'PR-2412-015-01',
    requestId: 'pr-015',
    itemName: 'Organic Tomatoes',
    location: 'Central Kitchen',
    name: 'Organic Tomatoes',
    description: 'Fresh organic tomatoes - shortage from store requisition',
    unit: 'kg',
    requestedQuantity: 30,
    quantityRequested: 30,
    quantityApproved: 0,
    deliveryLocationId: 'loc-003',
    requiredDate: new Date('2024-12-08'),
    priority: 'normal' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 20,
      onOrdered: 0,
      lastPrice: 3.00,
      lastOrderDate: new Date('2024-11-20'),
      lastVendor: 'Fresh Farm Produce',
      reorderLevel: 15,
      restockLevel: 50,
      averageMonthlyUsage: 80,
      inventoryUnit: 'kg',
    },
    currency: 'USD',
    price: 3.25,
    totalAmount: 97.50,
    status: PRStatus.InProgress,
    taxRate: 0,
    taxAmount: 0,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 97.50,
    deliveryDate: new Date('2024-12-08'),
    deliveryPoint: 'Central Kitchen Storage',
    createdDate: new Date('2024-12-05'),
    updatedDate: new Date('2024-12-05'),
    createdBy: 'System',
    updatedBy: 'System',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Fresh Vegetables',
    vendor: 'Fresh Farm Produce',
    comment: 'Generated from SR-2412-002 - stock shortage (had 20kg, needed 50kg)',
    adjustments: {
      discount: false,
      tax: false,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: 'FB-VEG-001',
  }
]

/**
 * PR-2412-016: Generated from SR-2412-007 (zero stock - full PR)
 * 100g Black Truffle - no stock available, full PR generation
 */
export const prFromSR007: MockPurchaseRequest = {
  id: 'pr-016',
  refNumber: 'PR-2412-016',
  requestNumber: 'PR-2412-016',
  requestDate: new Date('2024-12-17'),
  requiredDate: new Date('2024-12-22'),
  requestType: 'General',
  priority: 'normal',
  justification: 'Zero stock - Store Requisition SR-2412-007 requires full purchase',
  requestedBy: 'user-chef-001',
  departmentId: 'dept-003',
  locationId: 'loc-003',
  totalItems: 1,
  estimatedTotal: { amount: 500.00, currency: 'USD' },
  workflowStages: [],
  requestor: {
    name: 'Chef Maria Rodriguez',
    department: 'Food & Beverage'
  },
  status: PRStatus.InProgress,
  currentWorkflowStage: WorkflowStage.departmentHeadApproval,
  location: 'Central Kitchen',
  department: 'Food & Beverage',
  currency: 'USD',
  baseCurrencyCode: 'USD',
  baseSubTotalPrice: 500.00,
  subTotalPrice: 500.00,
  baseNetAmount: 500.00,
  netAmount: 500.00,
  baseDiscAmount: 0,
  discountAmount: 0,
  baseTaxAmount: 0,
  taxAmount: 0,
  baseTotalAmount: 500.00,
  totalAmount: 500.00,
  // Source requisition tracking
  sourceRequisitionId: 'sr-007',
  sourceRequisitionRefNo: 'SR-2412-007',
  sourceRequisitionItemIds: ['sri-007-01'],
}

export const prFromSR007Items: MockPurchaseRequestItem[] = [
  {
    id: 'PR-2412-016-01',
    requestId: 'pr-016',
    itemName: 'Black Truffle',
    location: 'Central Kitchen',
    name: 'Black Truffle',
    description: 'Premium black truffle for holiday menu - specialty item',
    unit: 'g',
    requestedQuantity: 100,
    quantityRequested: 100,
    quantityApproved: 0,
    deliveryLocationId: 'loc-003',
    requiredDate: new Date('2024-12-22'),
    priority: 'normal' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 0,
      onOrdered: 0,
      lastPrice: 4.80,
      lastOrderDate: new Date('2024-10-15'),
      lastVendor: 'Gourmet Specialty Foods',
      reorderLevel: 25,
      restockLevel: 100,
      averageMonthlyUsage: 50,
      inventoryUnit: 'g',
    },
    currency: 'USD',
    price: 5.00,
    totalAmount: 500.00,
    status: PRStatus.InProgress,
    taxRate: 0,
    taxAmount: 0,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 500.00,
    deliveryDate: new Date('2024-12-22'),
    deliveryPoint: 'Central Kitchen Cold Storage',
    createdDate: new Date('2024-12-17'),
    updatedDate: new Date('2024-12-17'),
    createdBy: 'System',
    updatedBy: 'System',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Specialty Items',
    vendor: 'Gourmet Specialty Foods',
    comment: 'Generated from SR-2412-007 - zero stock, full PR for specialty item',
    adjustments: {
      discount: false,
      tax: false,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: false,
    accountCode: 'FB-SPE-001',
  }
]

// ====== DEMO PR WITH DISPLAY VARIATIONS ======
// This PR demonstrates various display scenarios: comments, statuses, discounts, FOC items, unit conversions

export const demoPRWithVariations: MockPurchaseRequest = {
  id: 'pr-demo-001',
  refNumber: 'PR-2412-020',
  requestNumber: 'PR-2412-020',
  requestDate: new Date('2024-12-10'),
  requiredDate: new Date('2024-12-20'),
  requestType: 'General',
  priority: 'high',
  justification: 'Year-end F&B supplies for holiday events - includes specialty items and promotional goods',
  requestedBy: 'user-chef-002',
  departmentId: 'dept-003',
  locationId: 'loc-003',
  totalItems: 8,
  estimatedTotal: { amount: 6045.35, currency: 'USD' },
  workflowStages: [],
  requestor: {
    name: 'Executive Chef James Wilson',
    department: 'Food & Beverage'
  },
  status: PRStatus.InProgress,
  currentWorkflowStage: WorkflowStage.departmentHeadApproval,
  location: 'Main Kitchen',
  department: 'Food & Beverage',
  jobCode: 'FB-2412-HOLIDAY',
  currency: 'USD',
  baseCurrencyCode: 'THB',
  exchangeRate: 35.50,
  baseSubTotalPrice: 207497.50,
  subTotalPrice: 5845.00,
  baseNetAmount: 200308.75,
  netAmount: 5642.50,
  baseDiscAmount: 7188.75,
  discountAmount: 202.50,
  baseTaxAmount: 14301.18,
  taxAmount: 402.85,
  baseTotalAmount: 214609.93,
  totalAmount: 6045.35,
}

export const demoPRVariationsItems: MockPurchaseRequestItem[] = [
  // Item 1: Approved with detailed comment
  {
    id: 'PR-2412-020-01',
    requestId: 'pr-demo-001',
    itemName: 'Premium Angus Beef Tenderloin',
    location: 'Main Kitchen',
    name: 'Premium Angus Beef Tenderloin',
    description: 'USDA Prime grade, center-cut tenderloin, 2.5kg average weight',
    unit: 'Kg',
    requestedQuantity: 30,
    quantityRequested: 30,
    quantityApproved: 30,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-18'),
    priority: 'high' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 5,
      onOrdered: 0,
      lastPrice: 42.00,
      lastOrderDate: new Date('2024-11-15'),
      lastVendor: 'Premium Meats International',
      reorderLevel: 10,
      restockLevel: 40,
      averageMonthlyUsage: 25,
      inventoryUnit: 'Kg',
    },
    currency: 'USD',
    price: 45.00,
    totalAmount: 1350.00,
    status: PRStatus.Approved,
    taxRate: 0.07,
    taxAmount: 94.50,
    discountRate: 0.05,
    discountAmount: 67.50,
    netAmount: 1377.00,
    deliveryDate: new Date('2024-12-18'),
    deliveryPoint: 'Main Kitchen Cold Storage',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-12'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'F&B Director',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Fresh Meat',
    vendor: 'Premium Meats International',
    pricelistNumber: 'PL-2412-MEAT',
    comment: '⭐ PRIORITY: For Christmas Eve Gala Dinner (200 guests). Chef requests specific marbling grade. Coordinate with receiving team for 6 AM delivery. Store at -2°C immediately upon receipt.',
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-MEAT-001',
  },
  // Item 2: Pending approval, no comment
  {
    id: 'PR-2412-020-02',
    requestId: 'pr-demo-001',
    itemName: 'Fresh Atlantic Salmon',
    location: 'Main Kitchen',
    name: 'Fresh Atlantic Salmon',
    description: 'Norwegian salmon, whole fish, 4-5kg each',
    unit: 'Fish',
    requestedQuantity: 15,
    quantityRequested: 15,
    quantityApproved: 0,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-19'),
    priority: 'normal' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 52.00,
      lastOrderDate: new Date('2024-11-20'),
      lastVendor: 'Ocean Fresh Seafood',
      reorderLevel: 5,
      restockLevel: 20,
      averageMonthlyUsage: 12,
      inventoryUnit: 'Fish',
    },
    currency: 'USD',
    price: 55.00,
    totalAmount: 825.00,
    status: PRStatus.InProgress,
    taxRate: 0.07,
    taxAmount: 57.75,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 882.75,
    deliveryDate: new Date('2024-12-19'),
    deliveryPoint: 'Seafood Storage',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-10'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'Chef James Wilson',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Fresh Seafood',
    vendor: 'Ocean Fresh Seafood',
    pricelistNumber: 'PL-2412-SEAFOOD',
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-SEAFOOD-001',
  },
  // Item 3: FOC promotional item with explanation comment
  {
    id: 'PR-2412-020-03',
    requestId: 'pr-demo-001',
    itemName: 'Premium Olive Oil (Promotional)',
    location: 'Main Kitchen',
    name: 'Premium Olive Oil (Promotional)',
    description: 'Extra virgin Italian olive oil - COMPLIMENTARY from vendor',
    unit: 'Bottle',
    requestedQuantity: 6,
    quantityRequested: 6,
    quantityApproved: 6,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-18'),
    priority: 'low' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 12,
      onOrdered: 0,
      lastPrice: 0,
      lastOrderDate: new Date('2024-10-01'),
      lastVendor: 'Mediterranean Imports',
      reorderLevel: 5,
      restockLevel: 15,
      averageMonthlyUsage: 8,
      inventoryUnit: 'Bottle',
    },
    currency: 'USD',
    price: 0,
    totalAmount: 0,
    status: PRStatus.Approved,
    taxRate: 0,
    taxAmount: 0,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 0,
    deliveryDate: new Date('2024-12-18'),
    deliveryPoint: 'Dry Storage',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-11'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'Purchasing Manager',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Oils & Condiments',
    vendor: 'Mediterranean Imports',
    pricelistNumber: 'PL-2412-PROMO',
    comment: 'FREE promotional item from Mediterranean Imports - part of year-end vendor partnership program. Retail value: $35/bottle. For inventory tracking only.',
    adjustments: {
      discount: false,
      tax: false,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: true,
    accountCode: 'FB-PROMO-001',
  },
  // Item 4: Partially approved with reduction comment
  {
    id: 'PR-2412-020-04',
    requestId: 'pr-demo-001',
    itemName: 'Fresh Lobster Tails',
    location: 'Main Kitchen',
    name: 'Fresh Lobster Tails',
    description: 'Maine lobster tails, 6-8oz each, live delivery',
    unit: 'Pcs',
    requestedQuantity: 50,
    quantityRequested: 50,
    quantityApproved: 35,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-23'),
    priority: 'high' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 0,
      onOrdered: 0,
      lastPrice: 28.00,
      lastOrderDate: new Date('2024-11-28'),
      lastVendor: 'Ocean Fresh Seafood',
      reorderLevel: 10,
      restockLevel: 40,
      averageMonthlyUsage: 30,
      inventoryUnit: 'Pcs',
    },
    currency: 'USD',
    price: 32.00,
    totalAmount: 1120.00,
    status: PRStatus.Approved,
    taxRate: 0.07,
    taxAmount: 78.40,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 1198.40,
    deliveryDate: new Date('2024-12-23'),
    deliveryPoint: 'Seafood Cold Storage',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-13'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'F&B Director',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Fresh Seafood',
    vendor: 'Ocean Fresh Seafood',
    pricelistNumber: 'PL-2412-SEAFOOD',
    comment: '⚠️ QUANTITY REDUCED: Original request 50 pcs, approved 35 pcs due to budget constraints. Consider menu adjustment. Must be LIVE on arrival - reject DOA.',
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-SEAFOOD-002',
  },
  // Item 5: Rejected item
  {
    id: 'PR-2412-020-05',
    requestId: 'pr-demo-001',
    itemName: 'Imported Beluga Caviar',
    location: 'Main Kitchen',
    name: 'Imported Beluga Caviar',
    description: 'Premium Iranian Beluga caviar, 100g tin',
    unit: 'Tin',
    requestedQuantity: 5,
    quantityRequested: 5,
    quantityApproved: 0,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-20'),
    priority: 'low' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 0,
      onOrdered: 0,
      lastPrice: 420.00,
      lastOrderDate: new Date('2024-06-15'),
      lastVendor: 'Luxury Foods International',
      reorderLevel: 1,
      restockLevel: 3,
      averageMonthlyUsage: 1,
      inventoryUnit: 'Tin',
    },
    currency: 'USD',
    price: 480.00,
    totalAmount: 0,
    status: PRStatus.Cancelled,
    taxRate: 0.07,
    taxAmount: 0,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 0,
    deliveryDate: new Date('2024-12-20'),
    deliveryPoint: 'Main Kitchen Cold Storage',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-12'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'Finance Director',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Specialty Items',
    vendor: 'Luxury Foods International',
    pricelistNumber: 'PL-2412-LUXURY',
    comment: '❌ REJECTED: Exceeds specialty item budget allocation. Consider alternative: domestic paddlefish caviar at $85/tin. See approval note #REJ-2412-045.',
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-LUXURY-001',
  },
  // Item 6: Approved with high discount
  {
    id: 'PR-2412-020-06',
    requestId: 'pr-demo-001',
    itemName: 'Organic Mixed Greens',
    location: 'Main Kitchen',
    name: 'Organic Mixed Greens',
    description: 'Pre-washed organic salad mix, 500g bags',
    unit: 'Case',
    requestedQuantity: 20,
    quantityRequested: 20,
    quantityApproved: 20,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-18'),
    priority: 'normal' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 5,
      onOrdered: 0,
      lastPrice: 42.00,
      lastOrderDate: new Date('2024-12-01'),
      lastVendor: 'Fresh Farm Produce',
      reorderLevel: 8,
      restockLevel: 25,
      averageMonthlyUsage: 18,
      inventoryUnit: 'Case',
    },
    currency: 'USD',
    price: 45.00,
    totalAmount: 900.00,
    status: PRStatus.Approved,
    taxRate: 0.07,
    taxAmount: 56.70,
    discountRate: 0.15,
    discountAmount: 135.00,
    netAmount: 821.70,
    deliveryDate: new Date('2024-12-18'),
    deliveryPoint: 'Produce Cold Storage',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-11'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'Purchasing Manager',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Fresh Vegetables',
    vendor: 'Fresh Farm Produce',
    pricelistNumber: 'PL-2412-PRODUCE',
    comment: '💰 15% volume discount applied - year-end promotional pricing from vendor. Valid until Dec 31.',
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-VEG-002',
  },
  // Item 7: Draft status, long technical comment
  {
    id: 'PR-2412-020-07',
    requestId: 'pr-demo-001',
    itemName: 'Aged Parmigiano-Reggiano',
    location: 'Main Kitchen',
    name: 'Aged Parmigiano-Reggiano',
    description: '36-month aged DOP certified cheese, whole wheel approx 38kg',
    unit: 'Wheel',
    requestedQuantity: 2,
    quantityRequested: 2,
    quantityApproved: 0,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-17'),
    priority: 'normal' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 0.5, // Half wheel remaining
      onOrdered: 0,
      lastPrice: 520.00,
      lastOrderDate: new Date('2024-10-15'),
      lastVendor: 'Italian Cheese Importers',
      reorderLevel: 1,
      restockLevel: 3,
      averageMonthlyUsage: 1.5,
      inventoryUnit: 'Wheel',
    },
    currency: 'USD',
    price: 550.00,
    totalAmount: 1100.00,
    status: PRStatus.Draft,
    taxRate: 0.07,
    taxAmount: 77.00,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 1177.00,
    deliveryDate: new Date('2024-12-17'),
    deliveryPoint: 'Cheese Aging Room',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-10'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'Chef James Wilson',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Dairy & Cheese',
    vendor: 'Italian Cheese Importers',
    pricelistNumber: 'PL-2412-CHEESE',
    comment: '📋 SPECIFICATIONS: Must have DOP certification stamp visible. Verify 36-month minimum aging on label. Store in dedicated cheese room at 16-18°C, 80-85% humidity. One wheel for grated cheese station, one for tableside cheese trolley service. Alert sommelier for wine pairing suggestions.',
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-DAIRY-001',
  },
  // Item 8: Approved, urgent delivery comment
  {
    id: 'PR-2412-020-08',
    requestId: 'pr-demo-001',
    itemName: 'Fresh Black Truffles',
    location: 'Main Kitchen',
    name: 'Fresh Black Truffles',
    description: 'Périgord black winter truffles, Grade A, 50g minimum size',
    unit: 'g',
    requestedQuantity: 200,
    quantityRequested: 200,
    quantityApproved: 200,
    deliveryLocationId: 'main-kitchen',
    requiredDate: new Date('2024-12-23'),
    priority: 'high' as const,
    convertedToPO: false,
    inventoryInfo: {
      onHand: 0,
      onOrdered: 0,
      lastPrice: 2.50,
      lastOrderDate: new Date('2024-11-20'),
      lastVendor: 'Gourmet Specialty Foods',
      reorderLevel: 50,
      restockLevel: 150,
      averageMonthlyUsage: 100,
      inventoryUnit: 'g',
    },
    currency: 'USD',
    price: 2.75,
    totalAmount: 550.00,
    status: PRStatus.Approved,
    taxRate: 0.07,
    taxAmount: 38.50,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 588.50,
    deliveryDate: new Date('2024-12-23'),
    deliveryPoint: 'Main Kitchen - Chef Station',
    jobCode: 'FB-2412-HOLIDAY',
    createdDate: new Date('2024-12-10'),
    updatedDate: new Date('2024-12-14'),
    createdBy: 'Chef James Wilson',
    updatedBy: 'Executive Chef',
    itemCategory: 'Food & Beverage',
    itemSubcategory: 'Specialty Items',
    vendor: 'Gourmet Specialty Foods',
    pricelistNumber: 'PL-2412-TRUFFLE',
    comment: '🚨 CRITICAL: For Christmas Eve tasting menu. Delivery MUST arrive by 10 AM on Dec 23. Verify freshness - reject if older than 3 days from harvest. Notify head chef immediately upon receipt for quality inspection.',
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 35.50,
    foc: false,
    accountCode: 'FB-SPE-002',
  },
]

// ====== COMBINED EXPORTS ======

export const mockPurchaseRequests: MockPurchaseRequest[] = [
  samplePRData,
  prFromSR002,
  prFromSR007,
  demoPRWithVariations
];

export const mockPurchaseRequestItems: MockPurchaseRequestItem[] = [
  ...samplePRItems,
  ...prFromSR002Items,
  ...prFromSR007Items,
  ...demoPRVariationsItems
];

// ====== HELPER FUNCTIONS ======

/**
 * Get purchase request by ID
 */
export function getPurchaseRequestById(id: string): MockPurchaseRequest | undefined {
  return mockPurchaseRequests.find(pr => pr.id === id)
}

/**
 * Get purchase request by reference number
 */
export function getPurchaseRequestByRefNo(refNo: string): MockPurchaseRequest | undefined {
  return mockPurchaseRequests.find(pr => pr.refNumber === refNo)
}

/**
 * Get purchase requests generated from a specific store requisition
 */
export function getPurchaseRequestsBySourceRequisition(srId: string): MockPurchaseRequest[] {
  return mockPurchaseRequests.filter(pr => pr.sourceRequisitionId === srId)
}

/**
 * Get all purchase requests that were generated from store requisitions
 */
export function getSRGeneratedPurchaseRequests(): MockPurchaseRequest[] {
  return mockPurchaseRequests.filter(pr => pr.sourceRequisitionId !== undefined)
}

/**
 * Get purchase request items for a specific request
 */
export function getPurchaseRequestItems(requestId: string): MockPurchaseRequestItem[] {
  return mockPurchaseRequestItems.filter(item => item.requestId === requestId)
}
