/**
 * Mock Recipe Data
 * Centralized recipe mock data for the Carmen ERP application
 */

import { Recipe } from '@/lib/types'

export const mockRecipes: Recipe[] = [
  {
    id: 'recipe-001',
    recipeCode: 'RCP-001',
    name: 'Classic Margherita Pizza',
    description: 'Traditional Italian pizza with tomatoes, mozzarella, and basil',
    categoryId: 'category-001',
    cuisineTypeId: 'cuisine-001',
    status: 'published',
    complexity: 'moderate',
    yield: 4,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 pizza',
    yieldVariants: [
      {
        id: 'variant-001',
        name: 'Full Pizza',
        unit: 'SERVING',
        quantity: 4,
        conversionRate: 1.0,
        sellingPrice: { amount: 12.00, currency: 'USD' },
        costPerUnit: { amount: 3.50, currency: 'USD' },
        marginPercentage: 70.8,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-001',
        name: 'All-Purpose Flour',
        type: 'product',
        productId: 'product-003',
        quantity: 0.5,
        unit: 'kg',
        wastage: 2,
        yield: 98,
        netQuantity: 0.49,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 2.50, currency: 'USD' },
        totalCost: { amount: 1.25, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-002',
        name: 'Organic Tomatoes',
        type: 'product',
        productId: 'product-002',
        quantity: 0.3,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.285,
        inventoryQty: 0.3,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 1.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-003',
        name: 'Fresh Basil',
        type: 'product',
        productId: 'product-004',
        quantity: 1,
        unit: 'bunch',
        wastage: 10,
        yield: 90,
        netQuantity: 0.9,
        inventoryQty: 1,
        inventoryUnit: 'bunch',
        conversionFactor: 1.0,
        costPerUnit: { amount: 1.50, currency: 'USD' },
        totalCost: { amount: 1.50, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-001',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Dough',
        description: 'Prepare pizza dough with flour and water',
        duration: 15,
        equipments: ['Mixing Bowl'],
        tools: ['Measuring Cup', 'Whisk'],
        isPortionable: true
      },
      {
        id: 'step-002',
        order: 2,
        stepNumber: '2',
        title: 'Roll Dough',
        description: 'Roll out dough into circle',
        duration: 5,
        equipments: ['Work Surface'],
        tools: ['Rolling Pin'],
        isPortionable: true
      },
      {
        id: 'step-003',
        order: 3,
        stepNumber: '3',
        title: 'Add Toppings',
        description: 'Add tomato sauce and mozzarella cheese',
        duration: 5,
        equipments: [],
        tools: ['Ladle', 'Spoon'],
        isPortionable: true
      },
      {
        id: 'step-004',
        order: 4,
        stepNumber: '4',
        title: 'Bake',
        description: 'Bake at 220°C for 15 minutes',
        duration: 15,
        temperature: 220,
        equipments: ['Pizza Oven'],
        tools: ['Pizza Peel'],
        isPortionable: false
      },
      {
        id: 'step-005',
        order: 5,
        stepNumber: '5',
        title: 'Garnish',
        description: 'Garnish with fresh basil',
        duration: 2,
        equipments: [],
        tools: ['Knife'],
        isPortionable: true
      }
    ],
    prepTime: 30,
    cookTime: 15,
    totalTime: 45,
    totalCost: { amount: 14.00, currency: 'USD' },
    costPerPortion: { amount: 3.50, currency: 'USD' },
    foodCostPercentage: 29.2,
    requiredEquipment: ['Pizza Oven', 'Mixing Bowl', 'Work Surface'],
    skillLevel: 'intermediate',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Italian', 'Pizza', 'Main Course'],
    keywords: ['pizza', 'margherita', 'italian', 'tomato', 'basil'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-002',
    recipeCode: 'RCP-002',
    name: 'Mediterranean Salad',
    description: 'Fresh salad with tomatoes, olives, and olive oil dressing',
    categoryId: 'category-002',
    cuisineTypeId: 'cuisine-002',
    status: 'published',
    complexity: 'simple',
    yield: 2,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 bowl',
    yieldVariants: [
      {
        id: 'variant-002',
        name: 'Regular Bowl',
        unit: 'SERVING',
        quantity: 2,
        conversionRate: 1.0,
        sellingPrice: { amount: 8.50, currency: 'USD' },
        costPerUnit: { amount: 2.25, currency: 'USD' },
        marginPercentage: 73.5,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-004',
        name: 'Organic Tomatoes',
        type: 'product',
        productId: 'product-002',
        quantity: 0.2,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.19,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 0.80, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-005',
        name: 'Premium Olive Oil',
        type: 'product',
        productId: 'product-001',
        quantity: 0.05,
        unit: 'bottle',
        wastage: 0,
        yield: 100,
        netQuantity: 0.05,
        inventoryQty: 0.05,
        inventoryUnit: 'bottle',
        conversionFactor: 1.0,
        costPerUnit: { amount: 15.00, currency: 'USD' },
        totalCost: { amount: 0.75, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-006',
        name: 'Fresh Basil',
        type: 'product',
        productId: 'product-004',
        quantity: 0.5,
        unit: 'bunch',
        wastage: 10,
        yield: 90,
        netQuantity: 0.45,
        inventoryQty: 0.5,
        inventoryUnit: 'bunch',
        conversionFactor: 1.0,
        costPerUnit: { amount: 1.50, currency: 'USD' },
        totalCost: { amount: 0.75, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-006',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Tomatoes',
        description: 'Dice tomatoes',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Chef Knife'],
        isPortionable: true
      },
      {
        id: 'step-007',
        order: 2,
        stepNumber: '2',
        title: 'Add Dressing',
        description: 'Add olive oil dressing',
        duration: 3,
        equipments: ['Mixing Bowl'],
        tools: ['Spoon'],
        isPortionable: true
      },
      {
        id: 'step-008',
        order: 3,
        stepNumber: '3',
        title: 'Garnish',
        description: 'Garnish with fresh basil',
        duration: 2,
        equipments: [],
        tools: ['Knife'],
        isPortionable: true
      },
      {
        id: 'step-009',
        order: 4,
        stepNumber: '4',
        title: 'Serve',
        description: 'Serve immediately',
        duration: 1,
        equipments: ['Serving Bowl'],
        tools: [],
        isPortionable: true
      }
    ],
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    totalCost: { amount: 4.50, currency: 'USD' },
    costPerPortion: { amount: 2.25, currency: 'USD' },
    foodCostPercentage: 26.5,
    requiredEquipment: ['Cutting Board', 'Mixing Bowl', 'Serving Bowl'],
    skillLevel: 'beginner',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isHalal: true,
    isKosher: true,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Mediterranean', 'Salad', 'Healthy'],
    keywords: ['salad', 'mediterranean', 'tomato', 'olive oil', 'healthy'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-003',
    recipeCode: 'RCP-003',
    name: 'Pasta Carbonara',
    description: 'Classic Italian pasta with eggs, cheese, and pancetta',
    categoryId: '2',
    cuisineTypeId: '1',
    status: 'published',
    complexity: 'moderate',
    yield: 4,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 plate',
    yieldVariants: [
      {
        id: 'variant-003',
        name: 'Single Serving',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 16.00, currency: 'USD' },
        costPerUnit: { amount: 4.25, currency: 'USD' },
        marginPercentage: 73.4,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-007',
        name: 'Spaghetti',
        type: 'product',
        productId: 'product-005',
        quantity: 0.4,
        unit: 'kg',
        wastage: 2,
        yield: 98,
        netQuantity: 0.392,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 3.00, currency: 'USD' },
        totalCost: { amount: 1.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-008',
        name: 'Eggs',
        type: 'product',
        productId: 'product-006',
        quantity: 4,
        unit: 'piece',
        wastage: 0,
        yield: 100,
        netQuantity: 4,
        inventoryQty: 4,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.50, currency: 'USD' },
        totalCost: { amount: 2.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-009',
        name: 'Pancetta',
        type: 'product',
        productId: 'product-007',
        quantity: 0.2,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.19,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 18.00, currency: 'USD' },
        totalCost: { amount: 3.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-010',
        order: 1,
        stepNumber: '1',
        title: 'Boil Pasta',
        description: 'Cook spaghetti in salted water until al dente',
        duration: 10,
        equipments: ['Large Pot'],
        tools: ['Colander'],
        isPortionable: true
      },
      {
        id: 'step-011',
        order: 2,
        stepNumber: '2',
        title: 'Cook Pancetta',
        description: 'Crisp pancetta in a large pan',
        duration: 5,
        equipments: ['Large Pan'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-012',
        order: 3,
        stepNumber: '3',
        title: 'Mix Sauce',
        description: 'Whisk eggs and cheese in a bowl',
        duration: 3,
        equipments: ['Mixing Bowl'],
        tools: ['Whisk'],
        isPortionable: true
      },
      {
        id: 'step-013',
        order: 4,
        stepNumber: '4',
        title: 'Combine',
        description: 'Toss hot pasta with egg mixture and pancetta',
        duration: 2,
        equipments: ['Serving Bowl'],
        tools: ['Tongs'],
        isPortionable: true
      }
    ],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    totalCost: { amount: 17.00, currency: 'USD' },
    costPerPortion: { amount: 4.25, currency: 'USD' },
    foodCostPercentage: 26.6,
    requiredEquipment: ['Large Pot', 'Large Pan', 'Mixing Bowl'],
    skillLevel: 'intermediate',
    allergens: ['Eggs', 'Gluten', 'Dairy'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Italian', 'Pasta', 'Main Course'],
    keywords: ['carbonara', 'pasta', 'italian', 'eggs', 'pancetta'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-004',
    recipeCode: 'RCP-004',
    name: 'Tiramisu',
    description: 'Classic Italian coffee-flavored dessert',
    categoryId: '3',
    cuisineTypeId: '1',
    status: 'published',
    complexity: 'complex',
    yield: 8,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 slice',
    yieldVariants: [
      {
        id: 'variant-004',
        name: 'Single Slice',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.125,
        sellingPrice: { amount: 9.00, currency: 'USD' },
        costPerUnit: { amount: 2.50, currency: 'USD' },
        marginPercentage: 72.2,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-010',
        name: 'Mascarpone Cheese',
        type: 'product',
        productId: 'product-008',
        quantity: 0.5,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.5,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 20.00, currency: 'USD' },
        totalCost: { amount: 10.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-011',
        name: 'Ladyfinger Cookies',
        type: 'product',
        productId: 'product-009',
        quantity: 24,
        unit: 'piece',
        wastage: 5,
        yield: 95,
        netQuantity: 22.8,
        inventoryQty: 24,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.30, currency: 'USD' },
        totalCost: { amount: 7.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-012',
        name: 'Espresso',
        type: 'product',
        productId: 'product-010',
        quantity: 0.3,
        unit: 'liter',
        wastage: 0,
        yield: 100,
        netQuantity: 0.3,
        inventoryQty: 0.3,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 5.00, currency: 'USD' },
        totalCost: { amount: 1.50, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-014',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Coffee',
        description: 'Brew espresso and let cool',
        duration: 10,
        equipments: ['Espresso Machine'],
        tools: ['Cup'],
        isPortionable: false
      },
      {
        id: 'step-015',
        order: 2,
        stepNumber: '2',
        title: 'Mix Cream',
        description: 'Whip mascarpone with eggs and sugar',
        duration: 8,
        equipments: ['Mixing Bowl'],
        tools: ['Electric Mixer'],
        isPortionable: true
      },
      {
        id: 'step-016',
        order: 3,
        stepNumber: '3',
        title: 'Layer',
        description: 'Dip ladyfingers in espresso and layer with cream',
        duration: 15,
        equipments: ['Baking Dish'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-017',
        order: 4,
        stepNumber: '4',
        title: 'Chill',
        description: 'Refrigerate for at least 4 hours',
        duration: 240,
        equipments: ['Refrigerator'],
        tools: [],
        isPortionable: false
      }
    ],
    prepTime: 35,
    cookTime: 0,
    totalTime: 275,
    totalCost: { amount: 20.00, currency: 'USD' },
    costPerPortion: { amount: 2.50, currency: 'USD' },
    foodCostPercentage: 27.8,
    requiredEquipment: ['Espresso Machine', 'Mixing Bowl', 'Baking Dish', 'Refrigerator'],
    skillLevel: 'advanced',
    allergens: ['Eggs', 'Gluten', 'Dairy'],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Italian', 'Dessert', 'Coffee'],
    keywords: ['tiramisu', 'dessert', 'italian', 'coffee', 'mascarpone'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-005',
    recipeCode: 'RCP-005',
    name: 'Pad Thai',
    description: 'Authentic Thai stir-fried rice noodles with peanuts and lime',
    categoryId: '2',
    cuisineTypeId: '8',
    status: 'published',
    complexity: 'moderate',
    yield: 2,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 plate',
    yieldVariants: [
      {
        id: 'variant-005',
        name: 'Single Plate',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.5,
        sellingPrice: { amount: 14.00, currency: 'USD' },
        costPerUnit: { amount: 4.00, currency: 'USD' },
        marginPercentage: 71.4,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-013',
        name: 'Rice Noodles',
        type: 'product',
        productId: 'product-011',
        quantity: 0.2,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.19,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 8.00, currency: 'USD' },
        totalCost: { amount: 1.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-014',
        name: 'Shrimp',
        type: 'product',
        productId: 'product-012',
        quantity: 0.15,
        unit: 'kg',
        wastage: 10,
        yield: 90,
        netQuantity: 0.135,
        inventoryQty: 0.15,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 25.00, currency: 'USD' },
        totalCost: { amount: 3.75, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-015',
        name: 'Bean Sprouts',
        type: 'product',
        productId: 'product-013',
        quantity: 0.1,
        unit: 'kg',
        wastage: 15,
        yield: 85,
        netQuantity: 0.085,
        inventoryQty: 0.1,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 0.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-016',
        name: 'Peanuts',
        type: 'product',
        productId: 'product-014',
        quantity: 0.05,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.0475,
        inventoryQty: 0.05,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 12.00, currency: 'USD' },
        totalCost: { amount: 0.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-018',
        order: 1,
        stepNumber: '1',
        title: 'Soak Noodles',
        description: 'Soak rice noodles in warm water for 20 minutes',
        duration: 20,
        equipments: ['Large Bowl'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-019',
        order: 2,
        stepNumber: '2',
        title: 'Prep Ingredients',
        description: 'Prepare shrimp, vegetables, and sauce',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Chef Knife', 'Mixing Bowl'],
        isPortionable: true
      },
      {
        id: 'step-020',
        order: 3,
        stepNumber: '3',
        title: 'Stir-Fry',
        description: 'Stir-fry noodles with shrimp and vegetables',
        duration: 8,
        temperature: 200,
        equipments: ['Wok'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-021',
        order: 4,
        stepNumber: '4',
        title: 'Garnish',
        description: 'Top with peanuts, lime, and cilantro',
        duration: 2,
        equipments: [],
        tools: ['Knife'],
        isPortionable: true
      }
    ],
    prepTime: 30,
    cookTime: 10,
    totalTime: 40,
    totalCost: { amount: 8.00, currency: 'USD' },
    costPerPortion: { amount: 4.00, currency: 'USD' },
    foodCostPercentage: 28.6,
    requiredEquipment: ['Wok', 'Large Bowl', 'Cutting Board'],
    skillLevel: 'intermediate',
    allergens: ['Shellfish', 'Peanuts'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Thai', 'Noodles', 'Main Course'],
    keywords: ['pad thai', 'noodles', 'thai', 'shrimp', 'peanuts'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-006',
    recipeCode: 'RCP-006',
    name: 'Green Curry',
    description: 'Aromatic Thai green curry with coconut milk',
    categoryId: '2',
    cuisineTypeId: '8',
    status: 'published',
    complexity: 'moderate',
    yield: 4,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 bowl',
    yieldVariants: [
      {
        id: 'variant-006',
        name: 'Single Bowl',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 15.00, currency: 'USD' },
        costPerUnit: { amount: 4.50, currency: 'USD' },
        marginPercentage: 70.0,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-017',
        name: 'Coconut Milk',
        type: 'product',
        productId: 'product-015',
        quantity: 0.4,
        unit: 'liter',
        wastage: 0,
        yield: 100,
        netQuantity: 0.4,
        inventoryQty: 0.4,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 8.00, currency: 'USD' },
        totalCost: { amount: 3.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-018',
        name: 'Chicken Breast',
        type: 'product',
        productId: 'product-016',
        quantity: 0.5,
        unit: 'kg',
        wastage: 10,
        yield: 90,
        netQuantity: 0.45,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 14.00, currency: 'USD' },
        totalCost: { amount: 7.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-019',
        name: 'Green Curry Paste',
        type: 'product',
        productId: 'product-017',
        quantity: 0.1,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.1,
        inventoryQty: 0.1,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 15.00, currency: 'USD' },
        totalCost: { amount: 1.50, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-022',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Ingredients',
        description: 'Cut chicken and vegetables',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Chef Knife'],
        isPortionable: true
      },
      {
        id: 'step-023',
        order: 2,
        stepNumber: '2',
        title: 'Fry Paste',
        description: 'Fry curry paste in oil until fragrant',
        duration: 3,
        temperature: 180,
        equipments: ['Large Pot'],
        tools: ['Wooden Spoon'],
        isPortionable: true
      },
      {
        id: 'step-024',
        order: 3,
        stepNumber: '3',
        title: 'Add Coconut Milk',
        description: 'Add coconut milk and bring to simmer',
        duration: 5,
        equipments: ['Large Pot'],
        tools: ['Ladle'],
        isPortionable: true
      },
      {
        id: 'step-025',
        order: 4,
        stepNumber: '4',
        title: 'Cook Chicken',
        description: 'Add chicken and vegetables, cook until done',
        duration: 15,
        temperature: 95,
        equipments: ['Large Pot'],
        tools: ['Spoon'],
        isPortionable: true
      }
    ],
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    totalCost: { amount: 18.00, currency: 'USD' },
    costPerPortion: { amount: 4.50, currency: 'USD' },
    foodCostPercentage: 30.0,
    requiredEquipment: ['Large Pot', 'Cutting Board'],
    skillLevel: 'intermediate',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: true,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Thai', 'Curry', 'Main Course'],
    keywords: ['green curry', 'thai', 'coconut', 'chicken', 'spicy'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-007',
    recipeCode: 'RCP-007',
    name: 'Tacos Al Pastor',
    description: 'Traditional Mexican pork tacos with pineapple',
    categoryId: '2',
    cuisineTypeId: '3',
    status: 'published',
    complexity: 'moderate',
    yield: 6,
    yieldUnit: 'TACO',
    basePortionSize: 3,
    servingSize: '3 tacos',
    yieldVariants: [
      {
        id: 'variant-007',
        name: 'Trio',
        unit: 'TACO',
        quantity: 3,
        conversionRate: 0.5,
        sellingPrice: { amount: 12.00, currency: 'USD' },
        costPerUnit: { amount: 3.50, currency: 'USD' },
        marginPercentage: 70.8,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-020',
        name: 'Pork Shoulder',
        type: 'product',
        productId: 'product-018',
        quantity: 0.5,
        unit: 'kg',
        wastage: 15,
        yield: 85,
        netQuantity: 0.425,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 12.00, currency: 'USD' },
        totalCost: { amount: 6.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-021',
        name: 'Corn Tortillas',
        type: 'product',
        productId: 'product-019',
        quantity: 6,
        unit: 'piece',
        wastage: 5,
        yield: 95,
        netQuantity: 5.7,
        inventoryQty: 6,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.40, currency: 'USD' },
        totalCost: { amount: 2.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-022',
        name: 'Pineapple',
        type: 'product',
        productId: 'product-020',
        quantity: 0.2,
        unit: 'kg',
        wastage: 40,
        yield: 60,
        netQuantity: 0.12,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 5.00, currency: 'USD' },
        totalCost: { amount: 1.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-026',
        order: 1,
        stepNumber: '1',
        title: 'Marinate Pork',
        description: 'Marinate pork in achiote and spices',
        duration: 120,
        equipments: ['Mixing Bowl'],
        tools: ['Spoon'],
        isPortionable: true
      },
      {
        id: 'step-027',
        order: 2,
        stepNumber: '2',
        title: 'Grill Pork',
        description: 'Grill marinated pork until charred',
        duration: 20,
        temperature: 220,
        equipments: ['Grill'],
        tools: ['Tongs'],
        isPortionable: true
      },
      {
        id: 'step-028',
        order: 3,
        stepNumber: '3',
        title: 'Slice Meat',
        description: 'Thinly slice grilled pork',
        duration: 5,
        equipments: ['Cutting Board'],
        tools: ['Sharp Knife'],
        isPortionable: true
      },
      {
        id: 'step-029',
        order: 4,
        stepNumber: '4',
        title: 'Assemble Tacos',
        description: 'Warm tortillas and fill with pork and pineapple',
        duration: 5,
        equipments: ['Griddle'],
        tools: ['Spatula'],
        isPortionable: true
      }
    ],
    prepTime: 130,
    cookTime: 25,
    totalTime: 155,
    totalCost: { amount: 10.50, currency: 'USD' },
    costPerPortion: { amount: 3.50, currency: 'USD' },
    foodCostPercentage: 29.2,
    requiredEquipment: ['Grill', 'Mixing Bowl', 'Cutting Board', 'Griddle'],
    skillLevel: 'intermediate',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Mexican', 'Tacos', 'Main Course'],
    keywords: ['tacos', 'al pastor', 'mexican', 'pork', 'pineapple'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-008',
    recipeCode: 'RCP-008',
    name: 'Guacamole',
    description: 'Fresh Mexican avocado dip with lime and cilantro',
    categoryId: '1',
    cuisineTypeId: '3',
    status: 'published',
    complexity: 'simple',
    yield: 4,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1/2 cup',
    yieldVariants: [
      {
        id: 'variant-008',
        name: 'Small Bowl',
        unit: 'SERVING',
        quantity: 4,
        conversionRate: 1.0,
        sellingPrice: { amount: 8.00, currency: 'USD' },
        costPerUnit: { amount: 2.00, currency: 'USD' },
        marginPercentage: 75.0,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-023',
        name: 'Avocados',
        type: 'product',
        productId: 'product-021',
        quantity: 3,
        unit: 'piece',
        wastage: 30,
        yield: 70,
        netQuantity: 2.1,
        inventoryQty: 3,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 2.00, currency: 'USD' },
        totalCost: { amount: 6.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-024',
        name: 'Lime',
        type: 'product',
        productId: 'product-022',
        quantity: 2,
        unit: 'piece',
        wastage: 50,
        yield: 50,
        netQuantity: 1,
        inventoryQty: 2,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.50, currency: 'USD' },
        totalCost: { amount: 1.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-025',
        name: 'Cilantro',
        type: 'product',
        productId: 'product-023',
        quantity: 1,
        unit: 'bunch',
        wastage: 20,
        yield: 80,
        netQuantity: 0.8,
        inventoryQty: 1,
        inventoryUnit: 'bunch',
        conversionFactor: 1.0,
        costPerUnit: { amount: 1.00, currency: 'USD' },
        totalCost: { amount: 1.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-030',
        order: 1,
        stepNumber: '1',
        title: 'Mash Avocados',
        description: 'Mash ripe avocados in a bowl',
        duration: 5,
        equipments: ['Mixing Bowl'],
        tools: ['Fork'],
        isPortionable: true
      },
      {
        id: 'step-031',
        order: 2,
        stepNumber: '2',
        title: 'Add Ingredients',
        description: 'Mix in lime juice, onion, cilantro, and seasonings',
        duration: 5,
        equipments: ['Mixing Bowl'],
        tools: ['Spoon'],
        isPortionable: true
      },
      {
        id: 'step-032',
        order: 3,
        stepNumber: '3',
        title: 'Serve',
        description: 'Serve immediately with chips',
        duration: 1,
        equipments: ['Serving Bowl'],
        tools: [],
        isPortionable: true
      }
    ],
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    totalCost: { amount: 8.00, currency: 'USD' },
    costPerPortion: { amount: 2.00, currency: 'USD' },
    foodCostPercentage: 25.0,
    requiredEquipment: ['Mixing Bowl', 'Serving Bowl'],
    skillLevel: 'beginner',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isHalal: true,
    isKosher: true,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Mexican', 'Appetizer', 'Dip'],
    keywords: ['guacamole', 'avocado', 'mexican', 'dip', 'lime'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-009',
    recipeCode: 'RCP-009',
    name: 'Classic Burger',
    description: 'American beef burger with lettuce, tomato, and cheese',
    categoryId: '2',
    cuisineTypeId: '9',
    status: 'published',
    complexity: 'simple',
    yield: 4,
    yieldUnit: 'BURGER',
    basePortionSize: 1,
    servingSize: '1 burger',
    yieldVariants: [
      {
        id: 'variant-009',
        name: 'Single Burger',
        unit: 'BURGER',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 13.00, currency: 'USD' },
        costPerUnit: { amount: 3.75, currency: 'USD' },
        marginPercentage: 71.2,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-026',
        name: 'Ground Beef',
        type: 'product',
        productId: 'product-024',
        quantity: 0.6,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.57,
        inventoryQty: 0.6,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 15.00, currency: 'USD' },
        totalCost: { amount: 9.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-027',
        name: 'Burger Buns',
        type: 'product',
        productId: 'product-025',
        quantity: 4,
        unit: 'piece',
        wastage: 0,
        yield: 100,
        netQuantity: 4,
        inventoryQty: 4,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.80, currency: 'USD' },
        totalCost: { amount: 3.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-028',
        name: 'Cheddar Cheese',
        type: 'product',
        productId: 'product-026',
        quantity: 4,
        unit: 'slice',
        wastage: 0,
        yield: 100,
        netQuantity: 4,
        inventoryQty: 4,
        inventoryUnit: 'slice',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.60, currency: 'USD' },
        totalCost: { amount: 2.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-033',
        order: 1,
        stepNumber: '1',
        title: 'Form Patties',
        description: 'Form beef into 4 equal patties',
        duration: 5,
        equipments: ['Cutting Board'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-034',
        order: 2,
        stepNumber: '2',
        title: 'Grill Patties',
        description: 'Grill burgers to desired doneness',
        duration: 10,
        temperature: 200,
        equipments: ['Grill'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-035',
        order: 3,
        stepNumber: '3',
        title: 'Add Cheese',
        description: 'Add cheese and let melt',
        duration: 2,
        equipments: ['Grill'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-036',
        order: 4,
        stepNumber: '4',
        title: 'Assemble',
        description: 'Toast buns and assemble burgers with toppings',
        duration: 3,
        equipments: ['Grill'],
        tools: ['Knife'],
        isPortionable: true
      }
    ],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    totalCost: { amount: 15.00, currency: 'USD' },
    costPerPortion: { amount: 3.75, currency: 'USD' },
    foodCostPercentage: 28.8,
    requiredEquipment: ['Grill', 'Cutting Board'],
    skillLevel: 'beginner',
    allergens: ['Gluten', 'Dairy'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['American', 'Burger', 'Main Course'],
    keywords: ['burger', 'american', 'beef', 'cheese', 'grill'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-010',
    recipeCode: 'RCP-010',
    name: 'BBQ Ribs',
    description: 'Slow-cooked American BBQ pork ribs with tangy sauce',
    categoryId: '2',
    cuisineTypeId: '9',
    status: 'published',
    complexity: 'complex',
    yield: 4,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1/2 rack',
    yieldVariants: [
      {
        id: 'variant-010',
        name: 'Half Rack',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 22.00, currency: 'USD' },
        costPerUnit: { amount: 6.50, currency: 'USD' },
        marginPercentage: 70.5,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-029',
        name: 'Pork Ribs',
        type: 'product',
        productId: 'product-027',
        quantity: 2,
        unit: 'kg',
        wastage: 30,
        yield: 70,
        netQuantity: 1.4,
        inventoryQty: 2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 10.00, currency: 'USD' },
        totalCost: { amount: 20.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-030',
        name: 'BBQ Sauce',
        type: 'product',
        productId: 'product-028',
        quantity: 0.4,
        unit: 'liter',
        wastage: 5,
        yield: 95,
        netQuantity: 0.38,
        inventoryQty: 0.4,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 12.00, currency: 'USD' },
        totalCost: { amount: 4.80, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      }
    ],
    preparationSteps: [
      {
        id: 'step-037',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Ribs',
        description: 'Remove membrane and apply dry rub',
        duration: 15,
        equipments: ['Cutting Board'],
        tools: ['Paper Towel', 'Knife'],
        isPortionable: true
      },
      {
        id: 'step-038',
        order: 2,
        stepNumber: '2',
        title: 'Low and Slow',
        description: 'Smoke ribs at low temperature',
        duration: 240,
        temperature: 110,
        equipments: ['Smoker'],
        tools: ['Thermometer'],
        isPortionable: false
      },
      {
        id: 'step-039',
        order: 3,
        stepNumber: '3',
        title: 'Glaze',
        description: 'Brush with BBQ sauce and caramelize',
        duration: 15,
        temperature: 180,
        equipments: ['Grill'],
        tools: ['Brush'],
        isPortionable: true
      },
      {
        id: 'step-040',
        order: 4,
        stepNumber: '4',
        title: 'Rest and Serve',
        description: 'Let rest and cut into portions',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Sharp Knife'],
        isPortionable: true
      }
    ],
    prepTime: 20,
    cookTime: 270,
    totalTime: 290,
    totalCost: { amount: 26.00, currency: 'USD' },
    costPerPortion: { amount: 6.50, currency: 'USD' },
    foodCostPercentage: 29.5,
    requiredEquipment: ['Smoker', 'Grill', 'Cutting Board'],
    skillLevel: 'advanced',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['American', 'BBQ', 'Main Course'],
    keywords: ['ribs', 'bbq', 'american', 'pork', 'smoked'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-011',
    recipeCode: 'RCP-011',
    name: 'Croissants',
    description: 'Classic French buttery laminated pastry',
    categoryId: '3',
    cuisineTypeId: '5',
    status: 'published',
    complexity: 'advanced',
    yield: 12,
    yieldUnit: 'PIECE',
    basePortionSize: 1,
    servingSize: '1 croissant',
    yieldVariants: [
      {
        id: 'variant-011',
        name: 'Single Croissant',
        unit: 'PIECE',
        quantity: 1,
        conversionRate: 0.0833,
        sellingPrice: { amount: 4.50, currency: 'USD' },
        costPerUnit: { amount: 1.00, currency: 'USD' },
        marginPercentage: 77.8,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-031',
        name: 'All-Purpose Flour',
        type: 'product',
        productId: 'product-003',
        quantity: 0.5,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.475,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 2.50, currency: 'USD' },
        totalCost: { amount: 1.25, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-032',
        name: 'Butter',
        type: 'product',
        productId: 'product-029',
        quantity: 0.3,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.285,
        inventoryQty: 0.3,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 18.00, currency: 'USD' },
        totalCost: { amount: 5.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-033',
        name: 'Milk',
        type: 'product',
        productId: 'product-030',
        quantity: 0.15,
        unit: 'liter',
        wastage: 0,
        yield: 100,
        netQuantity: 0.15,
        inventoryQty: 0.15,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 0.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-041',
        order: 1,
        stepNumber: '1',
        title: 'Make Dough',
        description: 'Mix flour, milk, and yeast, knead until smooth',
        duration: 20,
        equipments: ['Mixing Bowl'],
        tools: ['Stand Mixer'],
        isPortionable: true
      },
      {
        id: 'step-042',
        order: 2,
        stepNumber: '2',
        title: 'Laminate',
        description: 'Fold butter into dough in layers',
        duration: 60,
        equipments: ['Work Surface'],
        tools: ['Rolling Pin'],
        isPortionable: true
      },
      {
        id: 'step-043',
        order: 3,
        stepNumber: '3',
        title: 'Shape',
        description: 'Cut triangles and roll into croissant shapes',
        duration: 20,
        equipments: ['Work Surface'],
        tools: ['Knife', 'Rolling Pin'],
        isPortionable: true
      },
      {
        id: 'step-044',
        order: 4,
        stepNumber: '4',
        title: 'Proof',
        description: 'Let croissants rise until doubled',
        duration: 120,
        equipments: ['Proofing Box'],
        tools: [],
        isPortionable: false
      },
      {
        id: 'step-045',
        order: 5,
        stepNumber: '5',
        title: 'Bake',
        description: 'Bake until golden brown',
        duration: 20,
        temperature: 200,
        equipments: ['Oven'],
        tools: ['Baking Sheet'],
        isPortionable: false
      }
    ],
    prepTime: 100,
    cookTime: 20,
    totalTime: 240,
    totalCost: { amount: 12.00, currency: 'USD' },
    costPerPortion: { amount: 1.00, currency: 'USD' },
    foodCostPercentage: 22.2,
    requiredEquipment: ['Mixing Bowl', 'Stand Mixer', 'Work Surface', 'Oven', 'Proofing Box'],
    skillLevel: 'advanced',
    allergens: ['Gluten', 'Dairy'],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['French', 'Pastry', 'Breakfast'],
    keywords: ['croissant', 'french', 'pastry', 'butter', 'laminated'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-012',
    recipeCode: 'RCP-012',
    name: 'Ratatouille',
    description: 'Provençal vegetable stew with tomatoes and herbs',
    categoryId: '2-3',
    cuisineTypeId: '5',
    status: 'published',
    complexity: 'moderate',
    yield: 6,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 cup',
    yieldVariants: [
      {
        id: 'variant-012',
        name: 'Single Serving',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.167,
        sellingPrice: { amount: 11.00, currency: 'USD' },
        costPerUnit: { amount: 2.50, currency: 'USD' },
        marginPercentage: 77.3,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-034',
        name: 'Eggplant',
        type: 'product',
        productId: 'product-031',
        quantity: 0.4,
        unit: 'kg',
        wastage: 20,
        yield: 80,
        netQuantity: 0.32,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 5.00, currency: 'USD' },
        totalCost: { amount: 2.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-035',
        name: 'Zucchini',
        type: 'product',
        productId: 'product-032',
        quantity: 0.4,
        unit: 'kg',
        wastage: 15,
        yield: 85,
        netQuantity: 0.34,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 1.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-036',
        name: 'Bell Peppers',
        type: 'product',
        productId: 'product-033',
        quantity: 0.3,
        unit: 'kg',
        wastage: 25,
        yield: 75,
        netQuantity: 0.225,
        inventoryQty: 0.3,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 6.00, currency: 'USD' },
        totalCost: { amount: 1.80, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-037',
        name: 'Organic Tomatoes',
        type: 'product',
        productId: 'product-002',
        quantity: 0.5,
        unit: 'kg',
        wastage: 10,
        yield: 90,
        netQuantity: 0.45,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 2.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-046',
        order: 1,
        stepNumber: '1',
        title: 'Prep Vegetables',
        description: 'Slice all vegetables uniformly',
        duration: 20,
        equipments: ['Cutting Board'],
        tools: ['Chef Knife'],
        isPortionable: true
      },
      {
        id: 'step-047',
        order: 2,
        stepNumber: '2',
        title: 'Sauté Base',
        description: 'Cook onions and garlic until soft',
        duration: 8,
        temperature: 160,
        equipments: ['Dutch Oven'],
        tools: ['Wooden Spoon'],
        isPortionable: true
      },
      {
        id: 'step-048',
        order: 3,
        stepNumber: '3',
        title: 'Layer Vegetables',
        description: 'Layer sliced vegetables in circular pattern',
        duration: 15,
        equipments: ['Baking Dish'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-049',
        order: 4,
        stepNumber: '4',
        title: 'Bake',
        description: 'Bake covered, then uncovered until tender',
        duration: 45,
        temperature: 180,
        equipments: ['Oven'],
        tools: ['Foil'],
        isPortionable: false
      }
    ],
    prepTime: 35,
    cookTime: 55,
    totalTime: 90,
    totalCost: { amount: 15.00, currency: 'USD' },
    costPerPortion: { amount: 2.50, currency: 'USD' },
    foodCostPercentage: 22.7,
    requiredEquipment: ['Dutch Oven', 'Baking Dish', 'Oven', 'Cutting Board'],
    skillLevel: 'intermediate',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isHalal: true,
    isKosher: true,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['French', 'Vegetarian', 'Main Course'],
    keywords: ['ratatouille', 'french', 'vegetable', 'stew', 'provencal'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-013',
    recipeCode: 'RCP-013',
    name: 'Sushi Rolls',
    description: 'Traditional Japanese maki rolls with fresh fish and rice',
    categoryId: '2',
    cuisineTypeId: '6',
    status: 'published',
    complexity: 'advanced',
    yield: 8,
    yieldUnit: 'PIECE',
    basePortionSize: 8,
    servingSize: '8 pieces',
    yieldVariants: [
      {
        id: 'variant-013',
        name: 'Full Roll',
        unit: 'PIECE',
        quantity: 8,
        conversionRate: 1.0,
        sellingPrice: { amount: 18.00, currency: 'USD' },
        costPerUnit: { amount: 5.50, currency: 'USD' },
        marginPercentage: 69.4,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-038',
        name: 'Sushi Rice',
        type: 'product',
        productId: 'product-034',
        quantity: 0.2,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.19,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 8.00, currency: 'USD' },
        totalCost: { amount: 1.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-039',
        name: 'Salmon Fillet',
        type: 'product',
        productId: 'product-035',
        quantity: 0.15,
        unit: 'kg',
        wastage: 20,
        yield: 80,
        netQuantity: 0.12,
        inventoryQty: 0.15,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 35.00, currency: 'USD' },
        totalCost: { amount: 5.25, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-040',
        name: 'Nori Sheets',
        type: 'product',
        productId: 'product-036',
        quantity: 2,
        unit: 'piece',
        wastage: 10,
        yield: 90,
        netQuantity: 1.8,
        inventoryQty: 2,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.80, currency: 'USD' },
        totalCost: { amount: 1.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-041',
        name: 'Avocado',
        type: 'product',
        productId: 'product-021',
        quantity: 1,
        unit: 'piece',
        wastage: 30,
        yield: 70,
        netQuantity: 0.7,
        inventoryQty: 1,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 2.00, currency: 'USD' },
        totalCost: { amount: 2.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-050',
        order: 1,
        stepNumber: '1',
        title: 'Cook Rice',
        description: 'Cook and season sushi rice with vinegar',
        duration: 30,
        equipments: ['Rice Cooker'],
        tools: ['Mixing Bowl'],
        isPortionable: true
      },
      {
        id: 'step-051',
        order: 2,
        stepNumber: '2',
        title: 'Prepare Fillings',
        description: 'Slice salmon and avocado into strips',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Sharp Knife'],
        isPortionable: true
      },
      {
        id: 'step-052',
        order: 3,
        stepNumber: '3',
        title: 'Roll Sushi',
        description: 'Place ingredients on nori and roll tightly',
        duration: 15,
        equipments: ['Bamboo Mat'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-053',
        order: 4,
        stepNumber: '4',
        title: 'Slice and Serve',
        description: 'Slice roll into 8 pieces',
        duration: 5,
        equipments: ['Cutting Board'],
        tools: ['Sharp Knife'],
        isPortionable: true
      }
    ],
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    totalCost: { amount: 11.00, currency: 'USD' },
    costPerPortion: { amount: 5.50, currency: 'USD' },
    foodCostPercentage: 30.6,
    requiredEquipment: ['Rice Cooker', 'Bamboo Mat', 'Cutting Board'],
    skillLevel: 'advanced',
    allergens: ['Fish', 'Soy'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Japanese', 'Sushi', 'Main Course'],
    keywords: ['sushi', 'japanese', 'salmon', 'maki', 'roll'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-014',
    recipeCode: 'RCP-014',
    name: 'Ramen',
    description: 'Japanese noodle soup with rich broth and toppings',
    categoryId: '2',
    cuisineTypeId: '6',
    status: 'published',
    complexity: 'complex',
    yield: 4,
    yieldUnit: 'BOWL',
    basePortionSize: 1,
    servingSize: '1 bowl',
    yieldVariants: [
      {
        id: 'variant-014',
        name: 'Single Bowl',
        unit: 'BOWL',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 16.00, currency: 'USD' },
        costPerUnit: { amount: 4.75, currency: 'USD' },
        marginPercentage: 70.3,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-042',
        name: 'Ramen Noodles',
        type: 'product',
        productId: 'product-037',
        quantity: 0.4,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.38,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 6.00, currency: 'USD' },
        totalCost: { amount: 2.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-043',
        name: 'Pork Belly',
        type: 'product',
        productId: 'product-038',
        quantity: 0.4,
        unit: 'kg',
        wastage: 15,
        yield: 85,
        netQuantity: 0.34,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 16.00, currency: 'USD' },
        totalCost: { amount: 6.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-044',
        name: 'Chicken Stock',
        type: 'product',
        productId: 'product-039',
        quantity: 1.5,
        unit: 'liter',
        wastage: 0,
        yield: 100,
        netQuantity: 1.5,
        inventoryQty: 1.5,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 5.00, currency: 'USD' },
        totalCost: { amount: 7.50, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-045',
        name: 'Soft-Boiled Eggs',
        type: 'product',
        productId: 'product-006',
        quantity: 4,
        unit: 'piece',
        wastage: 0,
        yield: 100,
        netQuantity: 4,
        inventoryQty: 4,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.50, currency: 'USD' },
        totalCost: { amount: 2.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-054',
        order: 1,
        stepNumber: '1',
        title: 'Make Broth',
        description: 'Simmer chicken stock with aromatics for rich flavor',
        duration: 180,
        temperature: 95,
        equipments: ['Large Pot'],
        tools: ['Ladle'],
        isPortionable: false
      },
      {
        id: 'step-055',
        order: 2,
        stepNumber: '2',
        title: 'Cook Pork',
        description: 'Braise pork belly until tender',
        duration: 90,
        temperature: 110,
        equipments: ['Braising Pan'],
        tools: ['Tongs'],
        isPortionable: true
      },
      {
        id: 'step-056',
        order: 3,
        stepNumber: '3',
        title: 'Prepare Toppings',
        description: 'Soft-boil eggs and prep garnishes',
        duration: 15,
        equipments: ['Small Pot'],
        tools: ['Timer'],
        isPortionable: true
      },
      {
        id: 'step-057',
        order: 4,
        stepNumber: '4',
        title: 'Cook Noodles',
        description: 'Boil noodles until al dente',
        duration: 3,
        equipments: ['Large Pot'],
        tools: ['Strainer'],
        isPortionable: true
      },
      {
        id: 'step-058',
        order: 5,
        stepNumber: '5',
        title: 'Assemble',
        description: 'Combine noodles, broth, pork, and toppings',
        duration: 5,
        equipments: ['Ramen Bowl'],
        tools: ['Ladle'],
        isPortionable: true
      }
    ],
    prepTime: 30,
    cookTime: 280,
    totalTime: 310,
    totalCost: { amount: 19.00, currency: 'USD' },
    costPerPortion: { amount: 4.75, currency: 'USD' },
    foodCostPercentage: 29.7,
    requiredEquipment: ['Large Pot', 'Braising Pan', 'Ramen Bowl'],
    skillLevel: 'advanced',
    allergens: ['Eggs', 'Gluten', 'Soy'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Japanese', 'Noodles', 'Main Course'],
    keywords: ['ramen', 'japanese', 'noodles', 'soup', 'pork'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-015',
    recipeCode: 'RCP-015',
    name: 'Butter Chicken',
    description: 'Creamy Indian curry with tender chicken in tomato sauce',
    categoryId: '2',
    cuisineTypeId: '4',
    status: 'published',
    complexity: 'moderate',
    yield: 6,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 plate',
    yieldVariants: [
      {
        id: 'variant-015',
        name: 'Single Serving',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.167,
        sellingPrice: { amount: 17.00, currency: 'USD' },
        costPerUnit: { amount: 4.50, currency: 'USD' },
        marginPercentage: 73.5,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-046',
        name: 'Chicken Thighs',
        type: 'product',
        productId: 'product-040',
        quantity: 1,
        unit: 'kg',
        wastage: 20,
        yield: 80,
        netQuantity: 0.8,
        inventoryQty: 1,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 12.00, currency: 'USD' },
        totalCost: { amount: 12.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-047',
        name: 'Heavy Cream',
        type: 'product',
        productId: 'product-041',
        quantity: 0.3,
        unit: 'liter',
        wastage: 0,
        yield: 100,
        netQuantity: 0.3,
        inventoryQty: 0.3,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 8.00, currency: 'USD' },
        totalCost: { amount: 2.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-048',
        name: 'Tomato Puree',
        type: 'product',
        productId: 'product-042',
        quantity: 0.4,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.4,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 1.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-049',
        name: 'Garam Masala',
        type: 'product',
        productId: 'product-043',
        quantity: 0.03,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.03,
        inventoryQty: 0.03,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 30.00, currency: 'USD' },
        totalCost: { amount: 0.90, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-059',
        order: 1,
        stepNumber: '1',
        title: 'Marinate Chicken',
        description: 'Marinate chicken in yogurt and spices for 2 hours',
        duration: 120,
        equipments: ['Mixing Bowl'],
        tools: ['Spoon'],
        isPortionable: true
      },
      {
        id: 'step-060',
        order: 2,
        stepNumber: '2',
        title: 'Cook Chicken',
        description: 'Pan-fry marinated chicken until golden',
        duration: 15,
        temperature: 180,
        equipments: ['Large Pan'],
        tools: ['Tongs'],
        isPortionable: true
      },
      {
        id: 'step-061',
        order: 3,
        stepNumber: '3',
        title: 'Make Sauce',
        description: 'Sauté onions, add tomato puree and spices',
        duration: 15,
        temperature: 160,
        equipments: ['Large Pot'],
        tools: ['Wooden Spoon'],
        isPortionable: true
      },
      {
        id: 'step-062',
        order: 4,
        stepNumber: '4',
        title: 'Combine',
        description: 'Add chicken and cream, simmer until thick',
        duration: 20,
        temperature: 95,
        equipments: ['Large Pot'],
        tools: ['Ladle'],
        isPortionable: true
      }
    ],
    prepTime: 130,
    cookTime: 50,
    totalTime: 180,
    totalCost: { amount: 27.00, currency: 'USD' },
    costPerPortion: { amount: 4.50, currency: 'USD' },
    foodCostPercentage: 26.5,
    requiredEquipment: ['Large Pan', 'Large Pot', 'Mixing Bowl'],
    skillLevel: 'intermediate',
    allergens: ['Dairy'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: true,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Indian', 'Curry', 'Main Course'],
    keywords: ['butter chicken', 'indian', 'curry', 'chicken', 'creamy'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-016',
    recipeCode: 'RCP-016',
    name: 'Naan Bread',
    description: 'Soft and fluffy Indian flatbread baked in tandoor',
    categoryId: '1',
    cuisineTypeId: '4',
    status: 'published',
    complexity: 'moderate',
    yield: 8,
    yieldUnit: 'PIECE',
    basePortionSize: 1,
    servingSize: '1 piece',
    yieldVariants: [
      {
        id: 'variant-016',
        name: 'Single Naan',
        unit: 'PIECE',
        quantity: 1,
        conversionRate: 0.125,
        sellingPrice: { amount: 3.50, currency: 'USD' },
        costPerUnit: { amount: 0.75, currency: 'USD' },
        marginPercentage: 78.6,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-050',
        name: 'All-Purpose Flour',
        type: 'product',
        productId: 'product-003',
        quantity: 0.5,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.475,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 2.50, currency: 'USD' },
        totalCost: { amount: 1.25, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-051',
        name: 'Yogurt',
        type: 'product',
        productId: 'product-044',
        quantity: 0.15,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.15,
        inventoryQty: 0.15,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 6.00, currency: 'USD' },
        totalCost: { amount: 0.90, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-052',
        name: 'Butter',
        type: 'product',
        productId: 'product-029',
        quantity: 0.1,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.095,
        inventoryQty: 0.1,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 18.00, currency: 'USD' },
        totalCost: { amount: 1.80, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-063',
        order: 1,
        stepNumber: '1',
        title: 'Make Dough',
        description: 'Mix flour, yogurt, yeast, and water into soft dough',
        duration: 15,
        equipments: ['Mixing Bowl'],
        tools: ['Wooden Spoon'],
        isPortionable: true
      },
      {
        id: 'step-064',
        order: 2,
        stepNumber: '2',
        title: 'Proof Dough',
        description: 'Let dough rise until doubled in size',
        duration: 90,
        equipments: ['Mixing Bowl'],
        tools: ['Damp Cloth'],
        isPortionable: false
      },
      {
        id: 'step-065',
        order: 3,
        stepNumber: '3',
        title: 'Shape',
        description: 'Divide and stretch dough into oval shapes',
        duration: 10,
        equipments: ['Work Surface'],
        tools: ['Rolling Pin'],
        isPortionable: true
      },
      {
        id: 'step-066',
        order: 4,
        stepNumber: '4',
        title: 'Bake',
        description: 'Bake in hot oven until puffed and charred',
        duration: 8,
        temperature: 250,
        equipments: ['Oven'],
        tools: ['Pizza Stone'],
        isPortionable: false
      },
      {
        id: 'step-067',
        order: 5,
        stepNumber: '5',
        title: 'Butter',
        description: 'Brush with melted butter immediately',
        duration: 2,
        equipments: [],
        tools: ['Brush'],
        isPortionable: true
      }
    ],
    prepTime: 25,
    cookTime: 10,
    totalTime: 125,
    totalCost: { amount: 6.00, currency: 'USD' },
    costPerPortion: { amount: 0.75, currency: 'USD' },
    foodCostPercentage: 21.4,
    requiredEquipment: ['Mixing Bowl', 'Oven', 'Work Surface'],
    skillLevel: 'intermediate',
    allergens: ['Gluten', 'Dairy'],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isHalal: true,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Indian', 'Bread', 'Side Dish'],
    keywords: ['naan', 'bread', 'indian', 'flatbread', 'tandoor'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-017',
    recipeCode: 'RCP-017',
    name: 'Bibimbap',
    description: 'Korean rice bowl with vegetables, meat, and gochujang',
    categoryId: '2',
    cuisineTypeId: '10',
    status: 'published',
    complexity: 'moderate',
    yield: 4,
    yieldUnit: 'BOWL',
    basePortionSize: 1,
    servingSize: '1 bowl',
    yieldVariants: [
      {
        id: 'variant-017',
        name: 'Single Bowl',
        unit: 'BOWL',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 15.00, currency: 'USD' },
        costPerUnit: { amount: 4.25, currency: 'USD' },
        marginPercentage: 71.7,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-053',
        name: 'White Rice',
        type: 'product',
        productId: 'product-045',
        quantity: 0.4,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.4,
        inventoryQty: 0.4,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 1.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-054',
        name: 'Beef Sirloin',
        type: 'product',
        productId: 'product-046',
        quantity: 0.3,
        unit: 'kg',
        wastage: 10,
        yield: 90,
        netQuantity: 0.27,
        inventoryQty: 0.3,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 22.00, currency: 'USD' },
        totalCost: { amount: 6.60, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-055',
        name: 'Spinach',
        type: 'product',
        productId: 'product-047',
        quantity: 0.2,
        unit: 'kg',
        wastage: 15,
        yield: 85,
        netQuantity: 0.17,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 5.00, currency: 'USD' },
        totalCost: { amount: 1.00, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-056',
        name: 'Gochujang',
        type: 'product',
        productId: 'product-048',
        quantity: 0.1,
        unit: 'kg',
        wastage: 0,
        yield: 100,
        netQuantity: 0.1,
        inventoryQty: 0.1,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 12.00, currency: 'USD' },
        totalCost: { amount: 1.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-068',
        order: 1,
        stepNumber: '1',
        title: 'Cook Rice',
        description: 'Cook rice until fluffy and set aside',
        duration: 20,
        equipments: ['Rice Cooker'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-069',
        order: 2,
        stepNumber: '2',
        title: 'Prep Vegetables',
        description: 'Blanch spinach and prepare other vegetables',
        duration: 15,
        equipments: ['Large Pot'],
        tools: ['Tongs'],
        isPortionable: true
      },
      {
        id: 'step-070',
        order: 3,
        stepNumber: '3',
        title: 'Cook Beef',
        description: 'Marinate and stir-fry beef until cooked',
        duration: 10,
        temperature: 200,
        equipments: ['Wok'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-071',
        order: 4,
        stepNumber: '4',
        title: 'Assemble',
        description: 'Arrange rice, vegetables, beef, and egg in bowl',
        duration: 5,
        equipments: ['Stone Bowl'],
        tools: [],
        isPortionable: true
      },
      {
        id: 'step-072',
        order: 5,
        stepNumber: '5',
        title: 'Serve',
        description: 'Top with gochujang and serve hot',
        duration: 2,
        equipments: [],
        tools: ['Spoon'],
        isPortionable: true
      }
    ],
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    totalCost: { amount: 17.00, currency: 'USD' },
    costPerPortion: { amount: 4.25, currency: 'USD' },
    foodCostPercentage: 28.3,
    requiredEquipment: ['Rice Cooker', 'Wok', 'Stone Bowl', 'Large Pot'],
    skillLevel: 'intermediate',
    allergens: ['Eggs', 'Soy'],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Korean', 'Rice Bowl', 'Main Course'],
    keywords: ['bibimbap', 'korean', 'rice', 'bowl', 'gochujang'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-018',
    recipeCode: 'RCP-018',
    name: 'Fried Rice',
    description: 'Classic Chinese fried rice with vegetables and eggs',
    categoryId: '2',
    cuisineTypeId: '2',
    status: 'published',
    complexity: 'simple',
    yield: 4,
    yieldUnit: 'SERVING',
    basePortionSize: 1,
    servingSize: '1 plate',
    yieldVariants: [
      {
        id: 'variant-018',
        name: 'Single Plate',
        unit: 'SERVING',
        quantity: 1,
        conversionRate: 0.25,
        sellingPrice: { amount: 10.00, currency: 'USD' },
        costPerUnit: { amount: 2.50, currency: 'USD' },
        marginPercentage: 75.0,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-057',
        name: 'White Rice (day-old)',
        type: 'product',
        productId: 'product-045',
        quantity: 0.6,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.57,
        inventoryQty: 0.6,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 2.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-058',
        name: 'Eggs',
        type: 'product',
        productId: 'product-006',
        quantity: 3,
        unit: 'piece',
        wastage: 0,
        yield: 100,
        netQuantity: 3,
        inventoryQty: 3,
        inventoryUnit: 'piece',
        conversionFactor: 1.0,
        costPerUnit: { amount: 0.50, currency: 'USD' },
        totalCost: { amount: 1.50, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-059',
        name: 'Mixed Vegetables',
        type: 'product',
        productId: 'product-049',
        quantity: 0.3,
        unit: 'kg',
        wastage: 10,
        yield: 90,
        netQuantity: 0.27,
        inventoryQty: 0.3,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 6.00, currency: 'USD' },
        totalCost: { amount: 1.80, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      },
      {
        id: 'ingredient-060',
        name: 'Soy Sauce',
        type: 'product',
        productId: 'product-050',
        quantity: 0.05,
        unit: 'liter',
        wastage: 0,
        yield: 100,
        netQuantity: 0.05,
        inventoryQty: 0.05,
        inventoryUnit: 'liter',
        conversionFactor: 1.0,
        costPerUnit: { amount: 8.00, currency: 'USD' },
        totalCost: { amount: 0.40, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 4
      }
    ],
    preparationSteps: [
      {
        id: 'step-073',
        order: 1,
        stepNumber: '1',
        title: 'Prep Ingredients',
        description: 'Dice vegetables and beat eggs',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Chef Knife', 'Whisk'],
        isPortionable: true
      },
      {
        id: 'step-074',
        order: 2,
        stepNumber: '2',
        title: 'Scramble Eggs',
        description: 'Scramble eggs in hot wok and set aside',
        duration: 3,
        temperature: 200,
        equipments: ['Wok'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-075',
        order: 3,
        stepNumber: '3',
        title: 'Stir-Fry',
        description: 'Stir-fry vegetables, then add rice',
        duration: 5,
        temperature: 220,
        equipments: ['Wok'],
        tools: ['Spatula'],
        isPortionable: true
      },
      {
        id: 'step-076',
        order: 4,
        stepNumber: '4',
        title: 'Season',
        description: 'Add soy sauce, eggs, and mix well',
        duration: 3,
        temperature: 200,
        equipments: ['Wok'],
        tools: ['Spatula'],
        isPortionable: true
      }
    ],
    prepTime: 10,
    cookTime: 12,
    totalTime: 22,
    totalCost: { amount: 10.00, currency: 'USD' },
    costPerPortion: { amount: 2.50, currency: 'USD' },
    foodCostPercentage: 25.0,
    requiredEquipment: ['Wok', 'Cutting Board'],
    skillLevel: 'beginner',
    allergens: ['Eggs', 'Soy'],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Chinese', 'Rice', 'Main Course'],
    keywords: ['fried rice', 'chinese', 'rice', 'eggs', 'stir-fry'],
    developedBy: 'user-001'
  }
]