import { Unit } from '@/lib/types'

export const mockUnits: Unit[] = [
  // Weight Units - INVENTORY type (for stock tracking)
  {
    id: "1",
    code: "KG",
    name: "Kilogram",
    symbol: "kg",
    description: "Standard metric weight unit for inventory tracking",
    type: "INVENTORY",
    category: "weight",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "2",
    code: "G",
    name: "Gram",
    symbol: "g",
    description: "Small metric weight unit",
    type: "INVENTORY",
    category: "weight",
    baseUnit: "KG",
    conversionFactor: 0.001,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  // Volume Units - INVENTORY type
  {
    id: "3",
    code: "L",
    name: "Liter",
    symbol: "L",
    description: "Standard metric volume unit for inventory tracking",
    type: "INVENTORY",
    category: "volume",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "4",
    code: "ML",
    name: "Milliliter",
    symbol: "mL",
    description: "Small metric volume unit",
    type: "INVENTORY",
    category: "volume",
    baseUnit: "L",
    conversionFactor: 0.001,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },

  // Count Units - ORDER type (for purchasing and receiving)
  {
    id: "5",
    code: "BOX",
    name: "Box",
    symbol: "box",
    description: "Standard packaging unit for ordering",
    type: "ORDER",
    category: "count",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "6",
    code: "CTN",
    name: "Carton",
    symbol: "ctn",
    description: "Carton packaging unit for bulk orders",
    type: "ORDER",
    category: "count",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "7",
    code: "PLT",
    name: "Pallet",
    symbol: "plt",
    description: "Large packaging unit for wholesale orders",
    type: "ORDER",
    category: "count",
    isActive: false,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  // Volume Measurement Units - MEASURE type (for ingredient measurements)
  {
    id: "8",
    code: "TSP",
    name: "Teaspoon",
    symbol: "tsp",
    description: "Small volume unit for ingredient measurements",
    type: "MEASURE",
    category: "volume",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "9",
    code: "TBSP",
    name: "Tablespoon",
    symbol: "tbsp",
    description: "Medium volume unit for ingredient measurements",
    type: "MEASURE",
    category: "volume",
    baseUnit: "TSP",
    conversionFactor: 3,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "10",
    code: "CUP",
    name: "Cup",
    symbol: "cup",
    description: "Standard cup measurement for ingredients",
    type: "MEASURE",
    category: "volume",
    baseUnit: "ML",
    conversionFactor: 240,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },

  // RECIPE type - Serving/Yield units (for recipe output)
  {
    id: "11",
    code: "SERVING",
    name: "Serving",
    symbol: "serving",
    description: "Standard serving unit for recipe yield",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "12",
    code: "PORTION",
    name: "Portion",
    symbol: "portion",
    description: "Individual portion for recipe yield",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "13",
    code: "PLATE",
    name: "Plate",
    symbol: "plate",
    description: "Plated serving for main courses",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "18",
    code: "BOWL",
    name: "Bowl",
    symbol: "bowl",
    description: "Bowl serving for soups and salads",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "19",
    code: "SLICE",
    name: "Slice",
    symbol: "slice",
    description: "Slice serving for pizzas, cakes, pies",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "20",
    code: "GLASS",
    name: "Glass",
    symbol: "glass",
    description: "Glass serving for beverages",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "21",
    code: "PIECE",
    name: "Piece",
    symbol: "piece",
    description: "Individual piece for desserts, appetizers",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "22",
    code: "TACO",
    name: "Taco",
    symbol: "taco",
    description: "Individual taco serving",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "23",
    code: "BURGER",
    name: "Burger",
    symbol: "burger",
    description: "Individual burger serving",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "24",
    code: "WRAP",
    name: "Wrap",
    symbol: "wrap",
    description: "Individual wrap serving",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "25",
    code: "SANDWICH",
    name: "Sandwich",
    symbol: "sandwich",
    description: "Individual sandwich serving",
    type: "RECIPE",
    category: "serving",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  // Additional Count Units - ORDER type
  {
    id: "14",
    code: "BAG",
    name: "Bag",
    symbol: "bag",
    description: "Bag packaging unit for ordering",
    type: "ORDER",
    category: "count",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "15",
    code: "CASE",
    name: "Case",
    symbol: "case",
    description: "Case packaging unit for bulk orders",
    type: "ORDER",
    category: "count",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  // Additional INVENTORY units
  {
    id: "16",
    code: "PC",
    name: "Piece",
    symbol: "pc",
    description: "Individual piece count for inventory",
    type: "INVENTORY",
    category: "count",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  // Additional MEASURE units (for ingredient measurements)
  {
    id: "17",
    code: "OZ",
    name: "Ounce",
    symbol: "oz",
    description: "Fluid ounce for ingredient measurements",
    type: "MEASURE",
    category: "volume",
    baseUnit: "ML",
    conversionFactor: 29.5735,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "26",
    code: "PINCH",
    name: "Pinch",
    symbol: "pinch",
    description: "Small amount for seasoning",
    type: "MEASURE",
    category: "volume",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  },
  {
    id: "27",
    code: "BUNCH",
    name: "Bunch",
    symbol: "bunch",
    description: "Bundle unit for herbs and vegetables",
    type: "MEASURE",
    category: "count",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    createdBy: "system",
  }
]
